In [28]:
import win32com.client as com
import os
import pandas as pd
import geopandas as gpd
import numpy as np
from functools import lru_cache
from collections import defaultdict

## __Open Visum .VER__

In [29]:
#Open network .ver file (from local disk not onedrive)
import win32com.client

#Visum = com.Dispatch("Visum.Visum.250") #Add .250 for Visum 25 version
Visum = com.Dispatch("Visum.Visum") #Visum 24 version
Visum.LoadVersion(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Visum Projects\RedOSMNX_AMG_24 - Copy.ver')
C = win32com.client.constants

In [39]:
Net = Visum.Net

## __Read Stop Points IMEPLAN__ (snapped)

In [30]:
# Need correction (must be 12,518) & agreed ox SP work better
bus_stops_buffer16 = gpd.read_file(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Insumos OSMNX\Transporte Publico\Snapped\buffer_and_hierarchy\bus_stops_snapped_buffer16.shp')
bus_stops_ox_noservice = gpd.read_file(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Insumos OSMNX\Transporte Publico\Snapped\ox_nearestEdge\bus_stops_snapped_ox.shp')
bus_stops_ox_position_processed = gpd.read_file(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Insumos OSMNX\Transporte Publico\Snapped\ox_nearestEdge\RelPos preprocess\bus_stops_ox_relpos_preprocessed.shp')
bus_stops_oxVisum_position_processed = gpd.read_file(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Visum Objects\Bus Stops Snapped to Visum Link\bus_stops_snapped.shp')

visum_links = gpd.read_file(r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Modelación Urbana - Red Vial Guadalajara\Insumos OSMNX\Visum\Edges\edges_visum.shp')

In [31]:
bus_stops_oxVisum_position_processed['NearestLin'].value_counts()

NearestLin
['residential']                     5104
['tertiary']                        3731
['secondary']                       1711
['primary']                         1312
['trunk']                            230
['unclassified']                     225
['service']                           44
['trunk_link']                        43
['primary_link']                      41
['living_street']                     18
['motorway_link']                     16
['tertiary_link']                     13
['secondary_link']                    12
['motorway']                          11
['tertiary', 'secondary']              2
['secondary_link', 'secondary']        2
['motorway_link', 'residential']       1
['trunk_link', 'residential']          1
['tertiary', 'trunk_link']             1
Name: count, dtype: int64

In [32]:
bus_stops = bus_stops_oxVisum_position_processed.copy()

### Transform bus stops CRS to EPSG:4326 to insert physical stop on x,y (Visum is in 4326)

In [33]:
print(f"Original bus stops CRS: {bus_stops.crs}")
bus_stops.to_crs(crs="EPSG:4326", inplace=True)
print(f"Updated bus stops CRS: {bus_stops.crs}")
bus_stops

Original bus stops CRS: EPSG:32613
Updated bus stops CRS: EPSG:4326

,id,stop_id,XCoord,YCoord,LinkNo,SnapDist_m,FromNodeNo,ToNodeNo,RelPosOnLi,NearestLin,route_list,SP_id,geometry
0,1.0,1,680976.456130,2.272737e+06,9238.0,7.332037,3304.0,30379.0,0.108069,['secondary'],"C116-V1,C116-V2,C15,N/A,T13A-C02,T13A-C03,Tron...",473,POINT (-103.26406 20.54483)
1,2.0,2,681483.253691,2.280846e+06,4352.0,6.928147,2340.0,1495.0,0.159889,['primary'],"C106,C19,C46-V1,C46-V2,N/A,Troncal 19 Periferico",267,POINT (-103.25837 20.61802)
2,3.0,3,700561.553323,2.281164e+06,65242.0,3.147165,24808.0,24811.0,0.824667,['residential'],"N/A,R1-Tepetates,R2-Zorrillos,T21 Zapotlanejo,...",1331,POINT (-103.07532 20.61896)
3,4.0,4,700707.084499,2.281320e+06,8267.0,10.889076,2947.0,30220.0,0.410244,['secondary'],"N/A,R1-Tepetates,R2-Zorrillos,T21 Zapotlanejo,...",432,POINT (-103.07391 20.62035)
4,5.0,5,700907.289266,2.281378e+06,8384.0,7.604439,2997.0,2948.0,0.605914,['secondary'],"N/A,R1-Tepetates,R2-Zorrillos,T21 Zapotlanejo,...",445,POINT (-103.07198 20.62085)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,NaN,12514,699396.250113,2.280168e+06,49413.0,10.040549,18239.0,18245.0,0.108508,['primary'],None,1157,POINT (-103.08661 20.61009)
12514,NaN,12515,699836.994172,2.280555e+06,49451.0,0.302038,18255.0,25555.0,0.900000,['primary'],None,1159,POINT (-103.08234 20.61354)
12515,NaN,12516,701461.660841,2.281479e+06,8288.0,2.373914,2957.0,2959.0,0.791024,['secondary'],None,434,POINT (-103.06665 20.6217)
12516,NaN,12517,701108.581247,2.281835e+06,8511.0,7.931644,3047.0,3072.0,0.824228,['tertiary'],None,449,POINT (-103.07 20.62496)
12517,4.0,12518,700707.084499,2.281320e+06,8267.0,10.889076,2947.0,30220.0,0.410244,['secondary'],"N/A,R1-Tepetates,R2-Zorrillos,T21 Zapotlanejo,...",432,POINT (-103.07391 20.62035)

## __Insert bus stops in Visum__

In [34]:
# Links
links = Visum.Net.Links
link_ids = links.GetMultiAttValues("No")  # ID del enlace
from_node = links.GetMultiAttValues("FromNodeNo")
to_node = links.GetMultiAttValues("ToNodeNo")
lenght_km = links.GetMultiAttValues("Length")
tsysset = links.GetMultiAttValues("TSysSet")

visum_links = pd.DataFrame({
    "LinkNo": [l[1] for l in link_ids],
    "FromNode": [fn[1] for fn in from_node],
    "ToNode": [tn[1] for tn in to_node],
    "Length": [l[1] for l in lenght_km],
    "TSysSet": [tsys[1] for tsys in tsysset]
})

visum_links

          LinkNo  FromNode    ToNode    Length TSysSet
0            1.0       1.0  103492.0  4.827825     B,C
1            1.0  103492.0       1.0  0.000000
2            2.0       1.0   15708.0  0.146029     B,C
3            2.0   15708.0       1.0  0.000000
4            3.0       2.0       3.0  0.520237     B,C
...          ...       ...       ...       ...     ...
593963  500924.0  213454.0  205191.0  0.010734   B,C,W
593964  500925.0  206297.0  213455.0  0.000000
593965  500925.0  213455.0  206297.0  0.010452      TL
593966  500926.0  206297.0  213456.0  0.000000
593967  500926.0  213456.0  206297.0  0.009371      TL

[593968 rows x 5 columns]

In [35]:
visum_links[visum_links['TSysSet'] == '']

          LinkNo  FromNode    ToNode  Length TSysSet
1            1.0  103492.0       1.0     0.0
3            2.0   15708.0       1.0     0.0
5            3.0       3.0       2.0     0.0
7            4.0    3068.0       2.0     0.0
9            5.0    7341.0       3.0     0.0
...          ...       ...       ...     ...     ...
593958  500922.0  205191.0  213452.0     0.0
593961  500923.0  213454.0  213453.0     0.0
593962  500924.0  205191.0  213454.0     0.0
593964  500925.0  206297.0  213455.0     0.0
593966  500926.0  206297.0  213456.0     0.0

[93042 rows x 5 columns]

In [11]:
x = visum_links.loc[(visum_links["FromNode"] == 1) & (visum_links["ToNode"] == 103492)]
x['Length']

0    4.827825
Name: Length, dtype: float64

In [36]:
# Function to check if a stop with the same ID already exists in Visum
def visum_SP_exists(stop_id):
    try:
        return Net.StopPoints.ItemByKey(stop_id) is not None
    except Exception:
        return False

def opposite_dir(fromNode, toNode):
    oppositeLink = visum_links.loc[(visum_links["FromNode"] == toNode) & (visum_links["ToNode"] == fromNode)] #get the opp. dir link of the one that holds the snap
    valid = oppositeLink.loc[
        (oppositeLink['Length'] > 0) &
        (oppositeLink['TSysSet'] != '')
    ]

    return not valid.empty

In [37]:
print(opposite_dir(1, 103492))

False

In [27]:
bus_stops.columns

Index(['id', 'stop_id', 'XCoord', 'YCoord', 'LinkNo', 'SnapDist_m',
       'FromNodeNo', 'ToNodeNo', 'RelPosOnLi', 'NearestLin', 'route_list',
       'SP_id', 'geometry'],
      dtype='object')

In [41]:
stops_not_inserted = []
inserted_sp = set()
sp_counter = 1

for SP in bus_stops.itertuples():
    # 1) Extract SP attributes
    stop_id = SP.stop_id #1 - 12,518
    id_imeplan = SP.id if not pd.isna(SP.id) else 0

    sp_id = SP.SP_id #1 - 11,400 (unificado por link)
    nearest_link = SP.LinkNo
    from_node = SP.FromNodeNo
    to_node = SP.ToNodeNo
    relative_position = SP.RelPosOnLi
    routes = SP.route_list
    #relpos_adjusted = SP.RelPos_New
    x = SP.geometry.x
    y = SP.geometry.y

    # 2) Add Stop & StopArea to Visum (12,518 physical stops)
    try:
        stop = Net.AddStop(stop_id, x, y)
        stop_area = Net.AddStopArea(stop_id, stop_id, from_node, x, y)

    except Exception as e:
        print(f"Error inserting {stop_id}: {e}")
        stops_not_inserted.append(stop_id)
        continue

    if sp_id not in inserted_sp:
        try:
            stop_point = Net.AddStopPointOnLink(sp_counter, stop_id, from_node, to_node, True)
            sp_counter += 1
            try:
                stop_point.SetAttValue("RelPos", relative_position)
                stop_point.SetAttValue('STOP_ID_IMEPLAN', id_imeplan)
                stop_point.SetAttValue('ROUTES', routes)
                stop_point.SetAttValue("TSysSet", "B")
            except Exception as e:
                print(f'Error setting attributes for {sp_id}: {e}')

            if opposite_dir(from_node, to_node):
                stop_point2 = Net.AddStopPointOnLink(sp_counter, stop_id, to_node, from_node, True)
                sp_counter += 1

                try:
                    stop_point2.SetAttValue("RelPos", 1-relative_position) #for it to be in the same position of opp. link
                    stop_point2.SetAttValue('STOP_ID_IMEPLAN', id_imeplan)
                    stop_point2.SetAttValue('ROUTES', routes)
                    stop_point2.SetAttValue("TSysSet", "B")
                except Exception as e:
                    print(f'Error setting attributes for {sp_id} partner: {e}')

            inserted_sp.add(sp_id)

        except Exception as e:
            print(f"Error inserting stop point for {stop_id}: {e}")
            stops_not_inserted.append(stop_id)
            continue
   
    stop.SetAttValue('STOP_ID_IMEPLAN', id_imeplan)

### __Update bus stops attributes in Visum__

In [149]:
route_numeric_attrs = {
    'mobiliario':'mobiliario',
    'iluminaci':'iluminacion',
    'señal_ver':'senal_ver',
    'señal_hor':'senal_hor',
    'banqueta':'banqueta',
    'vegetació':'vegetacion'
}

stop_points = Visum.Net.StopPoints


for SP in bus_stops.itertuples():
    # 1) Get SP from visum using stop_id
    stop_id = SP.stop_id
    stop_point = stop_points.ItemByKey(stop_id)

    # 2) Set routes attribute in stop_points
    for i in range(1,36):
        route=getattr(SP, f"ruta_{i}", None)
        if pd.notnull(route) and route != '' and route != 'N/A':
            stop_point.SetAttValue(f"ruta_{i}", route)

    # 3) Set numeric attributes in stop_points
    for col, visum_attr in route_numeric_attrs.items():
        value = getattr(SP, col, None)
        if pd.isna(value):
            value = 0
        stop_point.SetAttValue(visum_attr, value)

### Open them only for BUS (B) all so far which are the 12,518 are bus stops

In [150]:
for sp in Visum.Net.StopPoints:
    sp.SetAttValue("TSysSet", "B")

### Relative positions of existing SP per link
- to see if a new SP to be inserted conflicts with pre-existing SP in the link

In [79]:
# SP existentes por link
link_sp_positions = defaultdict(list)

for sp in Net.StopPoints:
    link_id = sp.AttValue("LinkNo")
    rel_pos = sp.AttValue("RelPos")

    link_sp_positions[link_id].append(rel_pos)

link_sp_positions

defaultdict(list, {})

### Neighbor links per Node
- to see if new SP to be inserted is too close to a SP of the neighboring link

In [27]:
node_in_links = defaultdict(list)
node_out_links = defaultdict(list)

for link in Net.Links:
    link_id = link.AttValue("No")
    from_n = link.AttValue("FromNodeNo")
    to_n = link.AttValue("ToNodeNo")

    key = (link_id, from_n, to_n)

    node_out_links[from_n].append(key)
    node_in_links[to_n].append(key)

In [28]:
node_in_links

defaultdict(list,
            {103492.0: [(1.0, 1.0, 103492.0),
              (199578.0, 78634.0, 103492.0),
              (258630.0, 47861.0, 103492.0)],
             1.0: [(1.0, 103492.0, 1.0),
              (2.0, 15708.0, 1.0),
              (59898.0, 22510.0, 1.0)],
             15708.0: [(2.0, 1.0, 15708.0),
              (42957.0, 21829.0, 15708.0),
              (58143.0, 21824.0, 15708.0)],
             3.0: [(3.0, 2.0, 3.0),
              (5.0, 7341.0, 3.0),
              (68762.0, 26341.0, 3.0)],
             2.0: [(3.0, 3.0, 2.0),
              (4.0, 3068.0, 2.0),
              (79712.0, 31294.0, 2.0)],
             3068.0: [(4.0, 2.0, 3068.0),
              (8574.0, 26414.0, 3068.0),
              (8576.0, 3069.0, 3068.0)],
             7341.0: [(5.0, 3.0, 7341.0),
              (20318.0, 7342.0, 7341.0),
              (20319.0, 7340.0, 7341.0)],
             9626.0: [(6.0, 4.0, 9626.0),
              (26657.0, 9627.0, 9626.0),
              (26658.0, 25881.0, 9626.0),
              (42563.0, 15567.0, 9626.0)],
             4.0: [(6.0, 9626.0, 4.0),
              (7.0, 15567.0, 4.0),
              (68144.0, 26054.0, 4.0)],
             15567.0: [(7.0, 4.0, 15567.0),
              (42561.0, 26132.0, 15567.0),
              (42563.0, 9626.0, 15567.0),
              (42564.0, 26053.0, 15567.0)],
             16637.0: [(8.0, 5.0, 16637.0),
              (7975.0, 2842.0, 16637.0),
              (45409.0, 31327.0, 16637.0)],
             5.0: [(8.0, 16637.0, 5.0),
              (9.0, 2842.0, 5.0),
              (64930.0, 24674.0, 5.0)],
             2842.0: [(9.0, 5.0, 2842.0),
              (7974.0, 29677.0, 2842.0),
              (7975.0, 16637.0, 2842.0)],
             8770.0: [(10.0, 6.0, 8770.0),
              (9042.0, 3234.0, 8770.0),
              (24332.0, 8773.0, 8770.0)],
             6.0: [(10.0, 8770.0, 6.0),
              (11.0, 21760.0, 6.0),
              (26439.0, 9546.0, 6.0)],
             21760.0: [(11.0, 6.0, 21760.0),
              (57976.0, 21756.0, 21760.0),
              (57984.0, 7.0, 21760.0)],
             32490.0: [(12.0, 7.0, 32490.0),
              (82505.0, 32491.0, 32490.0),
              (82506.0, 32489.0, 32490.0)],
             7.0: [(12.0, 32490.0, 7.0),
              (57978.0, 21757.0, 7.0),
              (57984.0, 21760.0, 7.0)],
             9381.0: [(13.0, 8.0, 9381.0),
              (25993.0, 9380.0, 9381.0),
              (25994.0, 22203.0, 9381.0),
              (25996.0, 22471.0, 9381.0)],
             8.0: [(13.0, 9381.0, 8.0),
              (14.0, 159.0, 8.0),
              (15.0, 22471.0, 8.0),
              (25992.0, 9380.0, 8.0)],
             159.0: [(14.0, 8.0, 159.0),
              (455.0, 554.0, 159.0),
              (456.0, 513.0, 159.0),
              (68581.0, 26254.0, 159.0)],
             22471.0: [(15.0, 8.0, 22471.0),
              (25996.0, 9381.0, 22471.0),
              (59804.0, 26675.0, 22471.0)],
             9686.0: [(16.0, 9.0, 9686.0),
              (26804.0, 25898.0, 9686.0),
              (67784.0, 25903.0, 9686.0)],
             9.0: [(16.0, 9686.0, 9.0),
              (17.0, 19477.0, 9.0),
              (72319.0, 27928.0, 9.0)],
             19477.0: [(17.0, 9.0, 19477.0),
              (26219.0, 9466.0, 19477.0),
              (52495.0, 25906.0, 19477.0),
              (52496.0, 29647.0, 19477.0)],
             27797.0: [(18.0, 10.0, 27797.0),
              (22.0, 11.0, 27797.0),
              (72028.0, 29672.0, 27797.0)],
             10.0: [(18.0, 27797.0, 10.0),
              (19.0, 7360.0, 10.0),
              (20.0, 7407.0, 10.0)],
             7360.0: [(19.0, 10.0, 7360.0),
              (20366.0, 7359.0, 7360.0),
              (20367.0, 25033.0, 7360.0)],
             7407.0: [(20.0, 10.0, 7407.0),
              (20377.0, 7363.0, 7407.0),
              (20505.0, 7411.0, 7407.0),
              (20506.0, 7412.0, 7407.0)],
             15402.0: [(21.0, 11.0, 15402.0),
              (26.0, 12.0, 15402.0),
              (42127.0, 15401.0, 15402.0)],
             11.0: [(21.0, 15402.0, 11.0),
              (22.0, 27797.0, 11.0),
              (23.0, 29671.0, 11.0)],
             29671.0: [(23.0, 11.0, 29671.0)],
             7400.0: [(24.0, 12.0, 7400.0),
              (20482.0, 7406.0, 7400.0),
              (20483.0, 15389.0, 7400.0),
              (20484.0, 15400.0, 7400.0)],
             12.0: [(24.0, 7400.0, 12.0),
              (25.0, 7363.0, 12.0),
              (26.0, 15402.0, 12.0)],
             7363.0: [(25.0, 12.0, 7363.0),
              (20376.0, 7406.0, 7363.0),
              (20377.0, 7407.0, 7363.0)],
             7369.0: [(27.0, 13.0, 7369.0),
              (20394.0, 7418.0, 7369.0),
              (20395.0, 7371.0, 7369.0)],
             13.0: [(27.0, 7369.0, 13.0),
              (28.0, 7368.0, 13.0),
              (20390.0, 7367.0, 13.0)],
             7368.0: [(28.0, 13.0, 7368.0),
              (20383.0, 7365.0, 7368.0),
              (20393.0, 7410.0, 7368.0)],
             25112.0: [(29.0, 14.0, 25112.0),
              (59034.0, 22194.0, 25112.0),
              (59088.0, 22212.0, 25112.0),
              (65968.0, 7489.0, 25112.0)],
             14.0: [(29.0, 25112.0, 14.0),
              (30.0, 7480.0, 14.0),
              (59032.0, 22194.0, 14.0)],
             7480.0: [(30.0, 14.0, 7480.0),
              (20230.0, 7306.0, 7480.0),
              (20704.0, 17325.0, 7480.0),
              (20705.0, 7528.0, 7480.0)],
             30532.0: [(31.0, 15.0, 30532.0),
              (78091.0, 30531.0, 30532.0),
              (495731.0, 208261.0, 30532.0)],
             15.0: [(31.0, 30532.0, 15.0),
              (32.0, 30538.0, 15.0),
              (33.0, 30539.0, 15.0),
              (34.0, 17478.0, 15.0)],
             30538.0: [(32.0, 15.0, 30538.0),
              (47564.0, 17486.0, 30538.0),
              (47570.0, 17490.0, 30538.0)],
             30539.0: [(33.0, 15.0, 30539.0),
              (37.0, 16.0, 30539.0),
              (78114.0, 30540.0, 30539.0)],
             17478.0: [(34.0, 15.0, 17478.0)],
             17479.0: [(35.0, 16.0, 17479.0),
              (47545.0, 25310.0, 17479.0),
              (47546.0, 30545.0, 17479.0),
              (47547.0, 17498.0, 17479.0)],
             16.0: [(35.0, 17479.0, 16.0),
              (36.0, 30533.0, 16.0),
              (37.0, 30539.0, 16.0),
              (38.0, 25308.0, 16.0)],
             30533.0: [(36.0, 16.0, 30533.0),
              (66309.0, 25267.0, 30533.0),
              (78099.0, 30956.0, 30533.0)],
             25308.0: [(38.0, 16.0, 25308.0),
              (39.0, 17.0, 25308.0),
              (66403.0, 25307.0, 25308.0)],
             17.0: [(39.0, 25308.0, 17.0)],
             30926.0: [(40.0, 18.0, 30926.0),
              (78923.0, 30927.0, 30926.0),
              (78924.0, 208294.0, 30926.0)],
             18.0: [(40.0, 30926.0, 18.0),
              (41.0, 24755.0, 18.0),
              (42.0, 21298.0, 18.0)],
             24755.0: [(41.0, 18.0, 24755.0),
              (11235.0, 3991.0, 24755.0),
              (65107.0, 24754.0, 24755.0)],
             21298.0: [(42.0, 18.0, 21298.0),
              (56815.0, 24379.0, 21298.0),
              (56816.0, 29777.0, 21298.0),
              (56818.0, 27852.0, 21298.0)],
             21303.0: [(43.0, 19.0, 21303.0),
              (49.0, 20.0, 21303.0),
              (56831.0, 30530.0, 21303.0)],
             19.0: [(43.0, 21303.0, 19.0),
              (44.0, 29775.0, 19.0),
              (45.0, 17032.0, 19.0),
              (46.0, 30851.0, 19.0)],
             29775.0: [(44.0, 19.0, 29775.0),
              (46398.0, 17031.0, 29775.0),
              (76289.0, 29774.0, 29775.0)],
             17032.0: [(45.0, 19.0, 17032.0)],
             30851.0: [(46.0, 19.0, 30851.0),
              (64235.0, 24381.0, 30851.0),
              (78773.0, 30850.0, 30851.0)],
             21300.0: [(47.0, 20.0, 21300.0),
              (56820.0, 21299.0, 21300.0),
              (56823.0, 21301.0, 21300.0)],
             20.0: [(47.0, 21300.0, 20.0),
              (48.0, 21299.0, 20.0),
              (49.0, 21303.0, 20.0)],
             21299.0: [(48.0, 20.0, 21299.0),
              (56819.0, 25304.0, 21299.0),
              (56820.0, 21300.0, 21299.0)],
             23491.0: [(50.0, 21.0, 23491.0),
              (11200.0, 3978.0, 23491.0),
              (62198.0, 28596.0, 23491.0)],
             21.0: [(50.0, 23491.0, 21.0),
              (51.0, 3978.0, 21.0),
              (73823.0, 28597.0, 21.0)],
             3978.0: [(51.0, 21.0, 3978.0),
              (11200.0, 23491.0, 3978.0),
              (11201.0, 23490.0, 3978.0),
              (11205.0, 3980.0, 3978.0)],
             11767.0: [(52.0, 22.0, 11767.0),
              (32457.0, 11760.0, 11767.0),
              (32478.0, 11768.0, 11767.0)],
             22.0: [(52.0, 11767.0, 22.0),
              (53.0, 11773.0, 22.0),
              (54.0, 27624.0, 22.0)],
             11773.0: [(53.0, 22.0, 11773.0),
              (32495.0, 11772.0, 11773.0),
              (32496.0, 11778.0, 11773.0)],
             27624.0: [(54.0, 22.0, 27624.0),
              (21484.0, 7746.0, 27624.0),
              (71628.0, 28608.0, 27624.0)],
             23217.0: [(55.0, 23.0, 23217.0),
              (11193.0, 3974.0, 23217.0),
              (23230.0, 8361.0, 23217.0)],
             23.0: [(55.0, 23217.0, 23.0),
              (56.0, 3974.0, 23.0),
              (57.0, 11757.0, 23.0)],
             3974.0: [(56.0, 23.0, 3974.0),
              (11188.0, 3973.0, 3974.0),
              (11193.0, 23217.0, 3974.0)],
             11757.0: [(57.0, 23.0, 11757.0),
              (23033.0, 8296.0, 11757.0),
              (32448.0, 28607.0, 11757.0)],
             3985.0: [(58.0, 24.0, 3985.0),
              (11215.0, 9569.0, 3985.0),
              (11216.0, 9566.0, 3985.0),
              (11218.0, 8363.0, 3985.0)],
             24.0: [(58.0, 3985.0, 24.0),
              (59.0, 15490.0, 24.0),
              (60.0, 15462.0, 24.0),
              (61.0, 8393.0, 24.0)],
             15490.0: [(59.0, 24.0, 15490.0),
              (23300.0, 8381.0, 15490.0),
              (26498.0, 9566.0, 15490.0),
              (26499.0, 9567.0, 15490.0)],
             15462.0: [(60.0, 24.0, 15462.0),
              (26501.0, 9568.0, 15462.0),
              (26506.0, 9569.0, 15462.0),
              (42298.0, 15467.0, 15462.0)],
             8393.0: [(61.0, 24.0, 8393.0),
              (23333.0, 9567.0, 8393.0),
              (23334.0, 9577.0, 8393.0),
              (23335.0, 9568.0, 8393.0)],
             11988.0: [(62.0, 25.0, 11988.0),
              (14994.0, 5369.0, 11988.0),
              (15006.0, 5372.0, 11988.0),
              (33104.0, 11987.0, 11988.0)],
             25.0: [(62.0, 11988.0, 25.0),
              (63.0, 5360.0, 25.0),
              (64.0, 11981.0, 25.0),
              (65.0, 5359.0, 25.0),
              (66.0, 5369.0, 25.0)],
             5360.0: [(63.0, 25.0, 5360.0),
              (14968.0, 5359.0, 5360.0),
              (14974.0, 12021.0, 5360.0),
              (14975.0, 11960.0, 5360.0)],
             11981.0: [(64.0, 25.0, 11981.0),
              (33081.0, 11987.0, 11981.0),
              (33082.0, 32319.0, 11981.0),
              (33084.0, 31782.0, 11981.0)],
             5359.0: [(65.0, 25.0, 5359.0),
              (14949.0, 5351.0, 5359.0),
              (14968.0, 5360.0, 5359.0),
              (14969.0, 29433.0, 5359.0)],
             5369.0: [(66.0, 25.0, 5369.0),
              (14994.0, 11988.0, 5369.0),
              (14995.0, 12022.0, 5369.0),
              (14996.0, 5373.0, 5369.0)],
             23782.0: [(67.0, 26.0, 23782.0),
              (62843.0, 23781.0, 23782.0),
              (62844.0, 23786.0, 23782.0)],
             26.0: [(67.0, 23782.0, 26.0),
              (68.0, 23780.0, 26.0),
              (62828.0, 23775.0, 26.0)],
             23780.0: [(68.0, 26.0, 23780.0),
              (62836.0, 23778.0, 23780.0),
              (62839.0, 23779.0, 23780.0)],
             9355.0: [(69.0, 27.0, 9355.0),
              (25936.0, 23735.0, 9355.0),
              (25937.0, 9362.0, 9355.0)],
             27.0: [(69.0, 9355.0, 27.0),
              (70.0, 9353.0, 27.0),
              (25934.0, 9354.0, 27.0)],
             9353.0: [(70.0, 27.0, 9353.0),
              (25933.0, 23752.0, 9353.0),
              (25952.0, 9362.0, 9353.0)],
             2769.0: [(71.0, 28.0, 2769.0),
              (7777.0, 2752.0, 2769.0),
              (7810.0, 15606.0, 2769.0)],
             28.0: [(71.0, 2769.0, 28.0),
              (72.0, 2753.0, 28.0),
              (29708.0, 10756.0, 28.0)],
             2753.0: [(72.0, 28.0, 2753.0),
              (7779.0, 2752.0, 2753.0),
              (7780.0, 22236.0, 2753.0)],
             23736.0: [(73.0, 29.0, 23736.0),
              (62741.0, 23679.0, 23736.0),
              (62744.0, 23737.0, 23736.0)],
             29.0: [(73.0, 23736.0, 29.0),
              (74.0, 28327.0, 29.0),
              (42662.0, 15606.0, 29.0)],
             28327.0: [(74.0, 29.0, 28327.0)],
             248.0: [(75.0, 30.0, 248.0),
              (679.0, 288.0, 248.0),
              (680.0, 273.0, 248.0),
              (23995.0, 8631.0, 248.0)],
             30.0: [(75.0, 248.0, 30.0),
              (76.0, 22841.0, 30.0),
              (58093.0, 21803.0, 30.0),
              (58094.0, 21804.0, 30.0)],
             22841.0: [(76.0, 30.0, 22841.0),
              (24001.0, 8633.0, 22841.0),
              (60668.0, 256.0, 22841.0)],
             21803.0: [(77.0, 31.0, 21803.0),
              (58093.0, 30.0, 21803.0),
              (58095.0, 21804.0, 21803.0)],
             31.0: [(77.0, 21803.0, 31.0),
              (78.0, 68.0, 31.0),
              (79.0, 32671.0, 31.0)],
             68.0: [(78.0, 31.0, 68.0),
              (176.0, 330.0, 68.0),
              (178.0, 32682.0, 68.0)],
             32671.0: [(79.0, 31.0, 32671.0),
              (699.0, 256.0, 32671.0),
              (83029.0, 32670.0, 32671.0),
              (83034.0, 32861.0, 32671.0)],
             374.0: [(80.0, 32.0, 374.0),
              (105.0, 40.0, 374.0),
              (1060.0, 49830.0, 374.0)],
             32.0: [(80.0, 374.0, 32.0),
              (81.0, 7230.0, 32.0),
              (82.0, 33.0, 32.0)],
             7230.0: [(81.0, 32.0, 7230.0),
              (20031.0, 117423.0, 7230.0),
              (20032.0, 117422.0, 7230.0)],
             33.0: [(82.0, 32.0, 33.0),
              (83.0, 41.0, 33.0),
              (84.0, 8185.0, 33.0)],
             41.0: [(83.0, 33.0, 41.0),
              (107.0, 408.0, 41.0),
              (108.0, 378.0, 41.0),
              (1049.0, 371.0, 41.0)],
             8185.0: [(84.0, 33.0, 8185.0),
              (309.0, 113.0, 8185.0),
              (22741.0, 8186.0, 8185.0)],
             30397.0: [(86.0, 34.0, 30397.0),
              (307.0, 112.0, 30397.0),
              (77803.0, 123751.0, 30397.0)],
             34.0: [(86.0, 30397.0, 34.0),
              (87.0, 42.0, 34.0),
              (88.0, 321.0, 34.0),
              (89.0, 8186.0, 34.0)],
             42.0: [(87.0, 34.0, 42.0),
              (110.0, 359.0, 42.0),
              (111.0, 115.0, 42.0),
              (113.0, 43.0, 42.0)],
             321.0: [(88.0, 34.0, 321.0),
              (91.0, 35.0, 321.0),
              (882.0, 49614.0, 321.0)],
             8186.0: [(89.0, 34.0, 8186.0),
              (22741.0, 8185.0, 8186.0),
              (22745.0, 80996.0, 8186.0)],
             31531.0: [(90.0, 35.0, 31531.0),
              (80231.0, 60.0, 31531.0),
              (80232.0, 125953.0, 31531.0)],
             35.0: [(90.0, 31531.0, 35.0),
              (91.0, 321.0, 35.0),
              (92.0, 36.0, 35.0),
              (112.0, 43.0, 35.0)],
             36.0: [(92.0, 35.0, 36.0),
              (93.0, 8099.0, 36.0),
              (94.0, 318.0, 36.0),
              (171.0, 66.0, 36.0)],
             8099.0: [(93.0, 36.0, 8099.0),
              (22487.0, 44.0, 8099.0),
              (22488.0, 8125.0, 8099.0)],
             318.0: [(94.0, 36.0, 318.0),
              (871.0, 315.0, 318.0),
              (872.0, 327.0, 318.0),
              (22485.0, 8098.0, 318.0)],
             39.0: [(95.0, 37.0, 39.0),
              (102.0, 385.0, 39.0),
              (104.0, 40.0, 39.0)],
             37.0: [(95.0, 39.0, 37.0),
              (96.0, 38.0, 37.0),
              (97.0, 32672.0, 37.0),
              (98.0, 286.0, 37.0)],
             38.0: [(96.0, 37.0, 38.0),
              (100.0, 22876.0, 38.0),
              (101.0, 378.0, 38.0)],
             32672.0: [(97.0, 37.0, 32672.0),
              (1091.0, 385.0, 32672.0),
              (83038.0, 34040.0, 32672.0)],
             286.0: [(98.0, 37.0, 286.0),
              (776.0, 33228.0, 286.0),
              (778.0, 22868.0, 286.0)],
             22876.0: [(100.0, 38.0, 22876.0),
              (60735.0, 22868.0, 22876.0),
              (60752.0, 22875.0, 22876.0)],
             378.0: [(101.0, 38.0, 378.0),
              (108.0, 41.0, 378.0),
              (1072.0, 40.0, 378.0)],
             385.0: [(102.0, 39.0, 385.0),
              (1090.0, 32673.0, 385.0),
              (1091.0, 32672.0, 385.0)],
             40.0: [(104.0, 39.0, 40.0),
              (105.0, 374.0, 40.0),
              (1072.0, 378.0, 40.0)],
             408.0: [(107.0, 41.0, 408.0),
              (1081.0, 381.0, 408.0),
              (1098.0, 387.0, 408.0),
              (1174.0, 8595.0, 408.0)],
             359.0: [(110.0, 42.0, 359.0),
              (1011.0, 390.0, 359.0),
              (1012.0, 402.0, 359.0)],
             115.0: [(111.0, 42.0, 115.0),
              (313.0, 402.0, 115.0),
              (314.0, 371.0, 115.0)],
             43.0: [(112.0, 35.0, 43.0),
              (113.0, 42.0, 43.0),
              (114.0, 44.0, 43.0),
              (132.0, 51.0, 43.0)],
             44.0: [(114.0, 43.0, 44.0),
              (115.0, 65.0, 44.0),
              (116.0, 8124.0, 44.0),
              (22487.0, 8099.0, 44.0)],
             65.0: [(115.0, 44.0, 65.0),
              (169.0, 8100.0, 65.0),
              (170.0, 52.0, 65.0)],
             8124.0: [(116.0, 44.0, 8124.0),
              (22563.0, 8123.0, 8124.0),
              (22564.0, 8125.0, 8124.0)],
             46.0: [(117.0, 45.0, 46.0),
              (120.0, 1708.0, 46.0),
              (122.0, 37802.0, 46.0)],
             45.0: [(117.0, 46.0, 45.0),
              (118.0, 49.0, 45.0),
              (119.0, 37795.0, 45.0)],
             49.0: [(118.0, 45.0, 49.0),
              (127.0, 8190.0, 49.0),
              (128.0, 118457.0, 49.0),
              (129.0, 37804.0, 49.0)],
             37795.0: [(119.0, 45.0, 37795.0),
              (95480.0, 37797.0, 37795.0),
              (95481.0, 37796.0, 37795.0),
              (95483.0, 78571.0, 37795.0)],
             1708.0: [(120.0, 46.0, 1708.0),
              (4965.0, 37803.0, 1708.0),
              (4966.0, 81048.0, 1708.0),
              (4967.0, 7449.0, 1708.0)],
             37802.0: [(122.0, 46.0, 37802.0),
              (95487.0, 37796.0, 37802.0),
              (95498.0, 37801.0, 37802.0)],
             54.0: [(123.0, 47.0, 54.0),
              (138.0, 62.0, 54.0),
              (139.0, 37803.0, 54.0),
              (140.0, 49615.0, 54.0)],
             47.0: [(123.0, 54.0, 47.0),
              (124.0, 78839.0, 47.0),
              (22580.0, 8130.0, 47.0)],
             78839.0: [(124.0, 47.0, 78839.0),
              (95502.0, 37803.0, 78839.0),
              (200059.0, 80805.0, 78839.0)],
             50.0: [(125.0, 48.0, 50.0),
              (130.0, 390.0, 50.0),
              (133.0, 51.0, 50.0)],
             48.0: [(125.0, 50.0, 48.0)],
             8190.0: [(127.0, 49.0, 8190.0),
              (306.0, 112.0, 8190.0),
              (22758.0, 81036.0, 8190.0)],
             118457.0: [(128.0, 49.0, 118457.0),
              (157.0, 60.0, 118457.0),
              (291846.0, 118456.0, 118457.0)],
             37804.0: [(129.0, 49.0, 37804.0),
              (95505.0, 49616.0, 37804.0),
              (95507.0, 111192.0, 37804.0)],
             390.0: [(130.0, 50.0, 390.0),

In [58]:
# Function to check if a new stop point can be added to a link without conflicting with existing stop points
def is_valid_position(link_id, rel_pos, threshold=0.001):
    existing = link_sp_positions.get(link_id, [])
    return not any(abs(rel_pos - p) < threshold for p in existing)

# Function to check if a stop with the same ID already exists in Visum
def visum_stop_exists(stop_id):
    try:
        return Net.Stops.ItemByKey(stop_id) is not None
    except Exception:
        return False

In [59]:
def conflicts_with_neighbors(link_id, rel_pos, threshold=0.001):
    selected_edge = visum_links[visum_links['LinkNo'] == link_id]
    # inicio del link → revisar link anterior
    if rel_pos < threshold:
        for sp in Net.StopPoints:
            if sp.AttValue("ToNodeNo") == selected_edge.FromNodeNo:
                if abs(1 - sp.AttValue("RelPos")) < threshold:
                    return True

    # final del link → revisar siguiente link
    if rel_pos > 1 - threshold:
        for sp in Net.StopPoints:
            if sp.AttValue("FromNodeNo") == selected_edge.ToNodeNo:
                if abs(sp.AttValue("RelPos")) < threshold:
                    return True

    return False

## __Create StopPoints on Visum__

In [67]:
bus_stops

,id,mobiliario,iluminaci,señal_ver,señal_hor,banqueta,vegetació,ruta_1,ruta_2,ruta_3,...,NearestNod,NearestN_1,NearestEdg,SnapDist_m,NearestLin,RelPosOnLi,FromNodeNo,ToNodeNo,NearestL_1,geometry
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Troncal 13A Solidaridad,Troncal 13B Solidaridad,T13A-C02,...,1771858665,3304,"(1771858665, 8778745267, 0)",8.207127,9238,0.116142,3304,30379,secondary,POINT (-103.26406 20.54483)
1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,Troncal 19 Periferico,C19,C46-V1,...,1700484749,2340,"(1677124239, 1700484749, 0)",8.441228,4352,0.817699,1495,2340,primary,POINT (-103.25837 20.61802)
2,3.0,0.0,1.0,0.0,0.0,1.0,0.0,T21 Zapotlanejo,T21-C01,R1-Tepetates,...,8407044728,24811,"(8407044724, 8407044728, 0)",6.982640,65242,0.850051,24808,24811,residential,POINT (-103.07532 20.61896)
3,4.0,0.0,1.0,0.0,0.0,1.0,0.0,T21 Zapotlanejo,T21-C01,R1-Tepetates,...,1746083332,2947,"(1746083332, 8778413347, 0)",10.527186,8267,0.339513,2947,30220,secondary,POINT (-103.07391 20.62035)
4,5.0,0.0,1.0,0.0,0.0,1.0,0.0,T21 Zapotlanejo,T21-C01,R1-Tepetates,...,1746083335,2948,"(1746090115, 1746083335, 0)",4.600218,8384,0.595657,2997,2948,secondary,POINT (-103.07198 20.62085)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,...,5987144952,16245,"(6322033098, 6322033110, 0)",8.663037,49413,0.110336,18239,18245,primary,POINT (-103.08661 20.61009)
12514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,...,8414023283,25555,"(6322039422, 8414023283, 0)",1.691836,49451,0.920860,18255,25555,primary,POINT (-103.08234 20.61354)
12515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,...,1746083377,2959,"(1746083353, 1746083377, 0)",2.215223,8288,0.801377,2957,2959,secondary,POINT (-103.06665 20.6217)
12516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,...,1746293814,3072,"(1746195132, 1746293814, 0)",5.281715,8511,0.772637,3047,3072,tertiary,POINT (-103.07 20.62496)
12517,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Zapo-Corraltos,Zapo-Tet,N/A,...,1746083332,2947,"(1746083332, 8778413347, 0)",10.527186,8267,0.339513,2947,30220,secondary,POINT (-103.07391 20.62035)

In [82]:
THRESH = 0.002
EDGE_EPS = 0.01   # para evitar bordes
NUDGE = 0.002     # para empujar posiciones

In [61]:
def clamp_position(rel):
    if rel < EDGE_EPS:
        return EDGE_EPS
    if rel > 1 - EDGE_EPS:
        return 1 - EDGE_EPS
    return rel

In [62]:
def conflict_same_link(link_id, rel):
    # Get relative positions of existing stop points on the same link
    # Check if the new stop point's relative position is too close to any existing stop point on the same link
    return any(abs(rel - p) < THRESH for p in link_sp_positions.get(link_id, []))

In [63]:
def conflict_neighbors(from_node, to_node, rel):
    #link = Net.Links.ItemByKey(link_id)
   # from_n = link.AttValue("FromNodeNo")
    #to_n = link.AttValue("ToNodeNo")

    # inicio
    if rel < THRESH:
        for l in node_in_links[from_node]:
            for p in link_sp_positions.get(l, []):
                if abs(1 - p) < THRESH:
                    return True

    # final
    if rel > 1 - THRESH:
        for l in node_out_links[to_node]:
            for p in link_sp_positions.get(l, []):
                if abs(p) < THRESH:
                    return True

    return False

In [64]:
def conflicts_with_neighbors(from_node, to_node, rel_pos, threshold=0.001):
    # inicio del link → revisar link anterior
    if rel_pos < threshold:
        for sp in Net.StopPoints:
            if sp.AttValue("ToNodeNo") == from_node:
                if abs(1 - sp.AttValue("RelPos")) < threshold:
                    return True

    # final del link → revisar siguiente link
    if rel_pos > 1 - threshold:
        for sp in Net.StopPoints:
            if sp.AttValue("FromNodeNo") == to_node:
                if abs(sp.AttValue("RelPos")) < threshold:
                    return True

    return False

In [78]:
def find_valid_position(stop_id, link_id, from_node, to_node, rel):
    rel = clamp_position(rel)
    position_adjusted = False

    # si la posición inicial está cerca de 0.5, sal de esa zona
    if abs(rel - 0.5) <= THRESH:
        rel = 0.5 + NUDGE if rel >= 0.5 else 0.5 - NUDGE
        rel = clamp_position(rel)

    for _ in range(10):  # máximo 10 intentos
        if not conflict_same_link(link_id, rel) and not conflict_neighbors(from_node, to_node, rel) and abs(rel-0.5) > THRESH:
            if position_adjusted:
                print(f'Relative position had to be adjusted for SP:{stop_id}')
            return rel
        
        rel += NUDGE
        rel = clamp_position(rel)
        position_adjusted = True

       # if rel > 1 - EDGE_EPS:
        #    rel = 0.5  # fallback al centro
        #    break

    print(f'Couldnt adjust position for SP: {stop_id}')
    return None  # no se pudo arreglar

In [76]:
bus_stops = bus_stops.sort_values(["NearestLin", "RelPosOnLi"])

In [85]:
THRESH = 0.001

def adjust_positions(group):
    positions = group["RelPosOnLi"].values.copy()
    
    for i in range(1, len(positions)):
        if positions[i] - positions[i-1] < THRESH:
            positions[i] = positions[i-1] + THRESH
    
    # clamp final
    positions = positions.clip(0.01, 0.99)
    
    group["RelPosAdj"] = positions
    return group

bus_stops_forVisum = bus_stops.groupby("NearestLin", group_keys=False).apply(adjust_positions)

C:\Users\AP03542515\AppData\Local\Temp\3\ipykernel_68624\3419638051.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  bus_stops_forVisum = bus_stops.groupby("NearestLin", group_keys=False).apply(adjust_positions)

In [86]:
bus_stops_forVisum

,id,mobiliario,iluminaci,señal_ver,señal_hor,banqueta,vegetació,ruta_1,ruta_2,ruta_3,...,NearestN_1,NearestEdg,SnapDist_m,NearestLin,RelPosOnLi,FromNodeNo,ToNodeNo,NearestL_1,geometry,RelPosAdj
5854,5946.0,0.0,0.0,0.0,0.0,0.0,0.0,T13A-C01,ATQ-IXT,Caj-SJuan,...,9,"(325713635, 6584813561, 0)",10.119210,17,0.048216,9,19477,primary,POINT (-103.25134 20.45556),0.048216
5852,5944.0,0.0,0.0,0.0,0.0,0.0,0.0,T13A-C01,Caj-SJuan,N/A,...,19477,"(325713635, 6584813561, 0)",6.213091,17,0.891631,9,19477,primary,POINT (-103.2519 20.45481),0.891631
4482,4523.0,0.0,0.0,0.0,0.0,1.0,0.0,Troncal 13C Solidaridad,T13C-C01,T13C-C02,...,25112,"(325722532, 8408128650, 0)",7.657755,29,0.711381,14,25112,secondary,POINT (-103.18825 20.57282),0.711381
7672,7817.0,1.0,0.0,0.0,0.0,0.0,0.0,Troncal 13C Solidaridad,T13C-C02,T13C-C03,...,15,"(325722722, 8784590905, 0)",8.944722,33,0.130065,15,30539,secondary,POINT (-103.18431 20.55397),0.130065
7783,7929.0,1.0,0.0,0.0,0.0,0.0,0.0,Troncal 13C Solidaridad,T13C-C02,T13C-C03,...,21303,"(325723400, 6821046163, 0)",6.811722,43,0.728447,19,21303,secondary,POINT (-103.1821 20.54415),0.728447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12034,12230.0,0.0,1.0,0.0,1.0,1.0,0.0,Troncal 11A Rio Nilo Guadalupe,T11A-C01,T11A-C02,...,134514,"(13542846568, 1343692894, 0)",10.244669,491835,0.663771,204958,134514,residential,POINT (-103.37655 20.67074),0.663771
10310,10480.0,0.0,0.0,0.0,0.0,0.0,0.0,Troncal 11A Rio Nilo Guadalupe,T11A-C01,T11A-C02,...,204967,"(13542914042, 1343692881, 0)",8.630558,491863,0.462211,204967,134511,residential,POINT (-103.37553 20.67227),0.462211
3558,3588.0,1.0,1.0,1.0,1.0,1.0,1.0,Troncal 12 Vallarta,N/A,N/A,...,204975,"(13542914075, 8311171474, 0)",9.529101,491886,0.332679,204975,184313,secondary,POINT (-103.37771 20.67451),0.332679
10309,10479.0,0.0,0.0,0.0,0.0,0.0,0.0,Troncal 11A Rio Nilo Guadalupe,T11A-C01,T11A-C02,...,176263,"(13542921732, 1342831090, 0)",9.094165,491945,0.853837,204994,134466,residential,POINT (-103.37981 20.67225),0.853837
9378,9534.0,0.0,1.0,0.0,0.0,1.0,0.0,Troncal 07 Enrique Diaz De Leon,T07-C01,T07-C02,...,186849,"(13545019649, 8359475137, 0)",11.860824,491964,0.766797,205000,186849,secondary,POINT (-103.35958 20.66697),0.766797

In [83]:

stops_not_inserted = []
stops_id_null = []

for stop in bus_stops.itertuples():
    stop_id = stop.id
    nearest_node = stop.NearestN_1
    nearest_link = stop.NearestLin
    from_node = stop.FromNodeNo
    to_node = stop.ToNodeNo
    relative_position = stop.RelPosOnLi
    x = stop.geometry.x
    y = stop.geometry.y

    # 1) Check if stop already exists
    if visum_stop_exists(stop_id):
        #print(f"STOP {stop_id} already exists in Visum, skipping.")
        continue

    # 2) If SP id is null
    if pd.isna(stop_id):
        stops_id_null.append(nearest_link)
        continue

    # 3) Use relative position OR adjust it if its too close to other SP
    rel_valid = find_valid_position(stop_id, nearest_link, from_node, to_node, relative_position)

    if rel_valid is None:
        print(f"Skipping {stop_id} - no valid position found")
        stops_not_inserted.append(stop_id)
        continue


    # 4) Add SP to Visum
    try:
        stop = Net.AddStop(stop_id, x, y)
        stop_area = Net.AddStopArea(stop_id, stop_id, nearest_node, x, y)
        stop_point = Net.AddStopPointOnLink(stop_id, stop_id, from_node, to_node, True)
    except Exception as e:
        print(f"Error inserting {stop_id}: {e}")
        stops_not_inserted.append(stop_id)
        continue

    # Change relative position of SP just created
    try:
        stop_point.SetAttValue("RelPos", rel_valid)
        # 🔁 actualizar memoria
        link_sp_positions[link_id].append(rel_valid)
    except Exception as e:
        print(f"RelPos failed for {stop_id}, keeping default (0.5): {e}")
        # 🔁 actualizar memoria
        link_sp_positions[link_id].append(0.5)

RelPos failed for 879.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 879 cannot be moved,  as the distance to the next stop point is (878) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2898.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2898 cannot be moved,  as the distance to the next stop point is (2897) < 0.001000.', None, 0, -2147352567), None)
Error inserting 2903.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 2903 cannot be inserted,  as the distance to the next stop point is (2898) < 0.001000.', None, 0, -2147352567), None)
Error inserting 2906.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 2906 cannot be inserted,  as the distance to the next stop point is (2898) < 0.001000.', None, 0, -2147352567), None)
Error inserting 579.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 579 cannot be inserted,  as the distance to the next stop point is (2898) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4275.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4275 cannot be moved,  as the distance to the next stop point is (800) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 224.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 224 cannot be moved,  as the distance to the next stop point is (223) < 0.001000.', None, 0, -2147352567), None)
Error inserting 222.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 222 cannot be inserted,  as the distance to the next stop point is (224) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2926.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2926 cannot be moved,  as the distance to the next stop point is (5052) < 0.001000.', None, 0, -2147352567), None)
Error inserting 2945.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 2945 cannot be inserted,  as the distance to the next stop point is (2926) < 0.001000.', None, 0, -2147352567), None)
Error inserting 12411.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 12411 cannot be inserted,  as the distance to the next stop point is (2926) < 0.001000.', None, 0, -2147352567), None)
Error inserting 12412.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 12412 cannot be inserted,  as the distance to the next stop point is (2926) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2361.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2361 cannot be moved,  as the distance to the next stop point is (2359) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4645.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4645 cannot be moved,  as the distance to the next stop point is (1611) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3282.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3282 cannot be moved,  as the distance to the next stop point is (3281) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3285.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3285 cannot be moved,  as the distance to the next stop point is (36) < 0.001000.', None, 0, -2147352567), None)
Error inserting 8966.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 8966 cannot be inserted,  as the distance to the next stop point is (3285) < 0.001000.', None, 0, -2147352567), None)
Error inserting 8971.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 8971 cannot be inserted,  as the distance to the next stop point is (3285) < 0.001000.', None, 0, -2147352567), None)
Error inserting 8975.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 8975 cannot be inserted,  as the distance to the next stop point is (3285) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 8801.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 8801 cannot be moved,  as the distance to the next stop point is (2978) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3083.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3083 cannot be moved,  as the distance to the next stop point is (3082) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4319.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4319 cannot be moved,  as the distance to the next stop point is (4318) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4126.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4126 cannot be moved,  as the distance to the next stop point is (113) < 0.001000.', None, 0, -2147352567), None)
Error inserting 4125.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 4125 cannot be inserted,  as the distance to the next stop point is (4126) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 974.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 974 cannot be moved,  as the distance to the next stop point is (973) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2646.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2646 cannot be moved,  as the distance to the next stop point is (2586) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5347.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5347 cannot be moved,  as the distance to the next stop point is (4957) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2099.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2099 cannot be moved,  as the distance to the next stop point is (2098) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4848.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4848 cannot be moved,  as the distance to the next stop point is (4843) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4908.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4908 cannot be moved,  as the distance to the next stop point is (404) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5065.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5065 cannot be moved,  as the distance to the next stop point is (2647) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5368.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5368 cannot be moved,  as the distance to the next stop point is (4266) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5430.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5430 cannot be moved,  as the distance to the next stop point is (771) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2834.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2834 cannot be moved,  as the distance to the next stop point is (2833) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5559.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5559 cannot be moved,  as the distance to the next stop point is (5881) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5077.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5077 cannot be moved,  as the distance to the next stop point is (5858) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5841.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5841 cannot be moved,  as the distance to the next stop point is (5840) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 2077.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 2077 cannot be moved,  as the distance to the next stop point is (2076) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10898.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10898 cannot be moved,  as the distance to the next stop point is (5066) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10756.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10756 cannot be moved,  as the distance to the next stop point is (2650) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 6023.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 6023 cannot be moved,  as the distance to the next stop point is (1538) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 1242.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 1242 cannot be moved,  as the distance to the next stop point is (1294) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 1359.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 1359 cannot be moved,  as the distance to the next stop point is (1358) < 0.001000.', None, 0, -2147352567), None)
Error inserting 1550.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 1550 cannot be inserted,  as the distance to the next stop point is (1359) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 1754.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 1754 cannot be moved,  as the distance to the next stop point is (1753) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10755.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10755 cannot be moved,  as the distance to the next stop point is (2648) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 6079.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 6079 cannot be moved,  as the distance to the next stop point is (6443) < 0.001000.', None, 0, -2147352567), None)
Couldnt adjust position for SP: 11223344.0
Skipping 11223344.0 - no valid position found
RelPos failed for 6647.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 6647 cannot be moved,  as the distance to the next stop point is (1778) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 8939.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 8939 cannot be moved,  as the distance to the next stop point is (3214) < 0.001000.', None, 0, -2147352567), None)
Error inserting 12175.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 12175 cannot be inserted,  as the distance to the next stop point is (8939) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10757.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10757 cannot be moved,  as the distance to the next stop point is (3081) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 5527.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 5527 cannot be moved,  as the distance to the next stop point is (5526) < 0.001000.', None, 0, -2147352567), None)
Error inserting 5533.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 5533 cannot be inserted,  as the distance to the next stop point is (5527) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4408.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4408 cannot be moved,  as the distance to the next stop point is (4407) < 0.001000.', None, 0, -2147352567), None)
Error inserting 4409.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 4409 cannot be inserted,  as the distance to the next stop point is (4408) < 0.001000.', None, 0, -2147352567), None)
Error inserting 10488.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 10488 cannot be inserted,  as the distance to the next stop point is (4408) < 0.001000.', None, 0, -2147352567), None)
Error inserting 10489.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 10489 cannot be inserted,  as the distance to the next stop point is (4408) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4345.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4345 cannot be moved,  as the distance to the next stop point is (4337) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 9194.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 9194 cannot be moved,  as the distance to the next stop point is (8401) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 8454.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 8454 cannot be moved,  as the distance to the next stop point is (8453) < 0.001000.', None, 0, -2147352567), None)
Error inserting 0.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'CNet::AddStopArea: Stop is no valid Stop Object', None, 0, -2147352567), None)
RelPos failed for 4049.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4049 cannot be moved,  as the distance to the next stop point is (4048) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9718.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9718 cannot be inserted,  as the distance to the next stop point is (4049) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9729.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9729 cannot be inserted,  as the distance to the next stop point is (4049) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9733.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9733 cannot be inserted,  as the distance to the next stop point is (4049) < 0.001000.', None, 0, -2147352567), None)
Error inserting 10854.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 10854 cannot be inserted,  as the distance to the next stop point is (4049) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3694.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3694 cannot be moved,  as the distance to the next stop point is (3693) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 4001.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 4001 cannot be moved,  as the distance to the next stop point is (4000) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 9756.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 9756 cannot be moved,  as the distance to the next stop point is (4152) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9765.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9765 cannot be inserted,  as the distance to the next stop point is (9756) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3610.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3610 cannot be moved,  as the distance to the next stop point is (3609) < 0.001000.', None, 0, -2147352567), None)
Error inserting 4158.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 4158 cannot be inserted,  as the distance to the next stop point is (3610) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3818.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3818 cannot be moved,  as the distance to the next stop point is (3817) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 3724.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 3724 cannot be moved,  as the distance to the next stop point is (3723) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 9579.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 9579 cannot be moved,  as the distance to the next stop point is (9578) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10829.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10829 cannot be moved,  as the distance to the next stop point is (9333) < 0.001000.', None, 0, -2147352567), None)
Error inserting 10830.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 10830 cannot be inserted,  as the distance to the next stop point is (10829) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 9685.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 9685 cannot be moved,  as the distance to the next stop point is (4003) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9686.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9686 cannot be inserted,  as the distance to the next stop point is (9685) < 0.001000.', None, 0, -2147352567), None)
Error inserting 9690.0: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'Stop point 9690 cannot be inserted,  as the distance to the next stop point is (9685) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 12355.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 12355 cannot be moved,  as the distance to the next stop point is (11749) < 0.001000.', None, 0, -2147352567), None)
RelPos failed for 10584.0, keeping default (0.5): (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2401', 'AttValue failed: Stop point 10584 cannot be moved,  as the distance to the next stop point is (9443) < 0.001000.', None, 0, -2147352567), None)

In [69]:
stops_not_inserted

[224.0,
 879.0,
 974.0,
 1294.0,
 1359.0,
 1550.0,
 1754.0,
 2035.0,
 2077.0,
 2099.0,
 2361.0,
 2646.0,
 2834.0,
 2897.0,
 2898.0,
 2903.0,
 2906.0,
 2945.0,
 3083.0,
 3282.0,
 3285.0,
 3610.0,
 3694.0,
 3724.0,
 3745.0,
 3818.0,
 3821.0,
 4001.0,
 4049.0,
 4126.0,
 4158.0,
 4275.0,
 4319.0,
 4345.0,
 4408.0,
 4409.0,
 4645.0,
 4848.0,
 4908.0,
 5052.0,
 5065.0,
 5347.0,
 5368.0,
 5430.0,
 5527.0,
 5533.0,
 5841.0,
 5858.0,
 5881.0,
 6023.0,
 6443.0,
 6647.0,
 0.0,
 8066.0,
 8098.0,
 8454.0,
 8784.0,
 8801.0,
 8939.0,
 8966.0,
 8971.0,
 8975.0,
 9194.0,
 9433.0,
 9439.0,
 9440.0,
 9579.0,
 9685.0,
 9686.0,
 9690.0,
 9718.0,
 9729.0,
 9733.0,
 9756.0,
 9765.0,
 10488.0,
 10489.0,
 10584.0,
 10755.0,
 10756.0,
 10757.0,
 10829.0,
 10830.0,
 10854.0,
 10898.0,
 12175.0,
 12355.0,
 12375.0,
 12380.0,
 12411.0,
 12412.0]