## Esto se uso para importar Puntos de Parada (from SHP) y Line Routes a Visum 
- Era cuando estabamos trabajando sobre la red de TransCAD 
- ya no usamos esta red y esto no se usa
- __sirve para la documentación de como crear objetos SP & LineRoute en Visum__

In [1]:
import win32com.client as com
import os
import pandas as pd
import numpy as np
from functools import lru_cache

## Open Visum File .ver

In [2]:
#Open network .ver file (from local disk not onedrive)
import win32com.client

Visum = com.Dispatch("Visum.Visum.250") #Add .250 for Visum 25 version
Visum.LoadVersion("C:/Users/AP03542515/Documents/Import RedGDL/RedGDL_withTravelTime.ver")
C = win32com.client.constants

In [3]:
#Select network
Net = Visum.Net

## Read StopPoints CSV (paradas logicas insumo de IMEPLAN)

In [4]:
sp2024_csv = r"C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Transporte Publico\Puntos de Parada\PuntosParada2024_Attributes.csv"
sp2024_df = pd.read_csv(sp2024_csv)
sp2024_df

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
0,1,1,1,0.000000,1,0.0,1.0,1.0,120551.0,1.0,85179,Parada
1,2,1,1,0.459851,2,459.0,1.0,2.0,140696.0,1.0,52849,Parada
2,3,1,1,0.646481,3,646.0,1.0,5.0,79908.0,-1.0,52902,Parada
3,4,1,1,0.872291,4,872.0,1.0,7.0,79910.0,-1.0,52904,Parada
4,5,1,1,1.219899,5,1219.0,1.0,9.0,144971.0,1.0,53616,Parada
...,...,...,...,...,...,...,...,...,...,...,...,...
45337,46314,1337,1,9.013195,46314,21640.0,521.0,210.0,117476.0,-1.0,82302,Parada
45338,46315,1337,1,9.230524,46315,21858.0,521.0,215.0,66355.0,-1.0,44351,Parada
45339,46316,1337,1,9.652481,46316,22280.0,521.0,218.0,66358.0,-1.0,44333,Parada
45340,46317,1337,1,0.042722,46317,NaN,NaN,NaN,NaN,NaN,45351,NaN
45341,46318,1337,1,0.281257,46318,12929.0,521.0,123.0,118927.0,1.0,45360,Parada

#### __comment:__ Los registros que tienen campo SECUENCIA en NULL... NO SIRVEN, hay que quitarlos
#### puede ser solo una parada en la ruta la que se borra o puede ser que toda una ruta no tenga secuencia en sus paradas (ej.1104, 1105, etc...)

In [119]:
no_sequence = sp2024_df[sp2024_df['SECUENCIA'].isna()]
no_sequence = no_sequence.sort_values(by=['ROUTE_ID'])
no_sequence

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
41396,44753,3,1,35.385487,44753,NaN,NaN,NaN,NaN,NaN,4547,Extra
41395,44754,5,1,35.384651,44754,NaN,NaN,NaN,NaN,NaN,4547,Extra
41334,44759,10,1,7.386519,44759,NaN,NaN,NaN,NaN,NaN,98295,Extra
41333,44760,11,1,28.117382,44760,NaN,NaN,NaN,NaN,NaN,98295,Extra
44531,45387,215,1,3.226703,45387,NaN,NaN,NaN,NaN,NaN,72865,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
45230,46207,1333,1,0.032434,46207,NaN,NaN,NaN,NaN,NaN,83646,NaN
45286,46263,1335,1,0.034565,46263,NaN,NaN,NaN,NaN,NaN,83646,NaN
45287,46264,1335,1,0.570972,46264,NaN,NaN,NaN,NaN,NaN,83429,NaN
45313,46290,1336,1,9.784491,46290,NaN,NaN,NaN,NaN,NaN,83653,NaN
45340,46317,1337,1,0.042722,46317,NaN,NaN,NaN,NaN,NaN,45351,NaN

In [ ]:
sp2024_withSequence = sp2024_df.dropna(subset=['SECUENCIA']) #1,568 registros sin SECUENCIA
len(sp2024_withSequence) #Quedaron 43,774 puntos de parada x Ruta

43774

### obtener paradas fisicas filtrando los unique NODES

In [15]:
#Unique nodes in sp2024_withSequence
unique_nodes = sp2024_withSequence["NODE"].unique()
len(unique_nodes)

7374

## Create Stop Points ON NODES

In [16]:
stop_point_no = 1

for node in unique_nodes:
    node_id = node
    
    #Add STOP
    stop = Net.AddStop(stop_point_no)
    #Add STOP AREA on NODE
    stop_area = Net.AddStopArea(stop_point_no, stop_point_no, node_id)
    #Add STOP POINT on NODE
    stop_point = Net.AddStopPointOnNode(stop_point_no, stop_point_no, node_id)

    
    #increment stop point number for next stop point (used for ids)
    stop_point_no += 1

### Read Stop Points from VISUM & join with Stop_Points CSV on NODE

In [17]:
visum_stop_points = pd.DataFrame({
    "No": [i[1] for i in Visum.Net.StopPoints.GetMultiAttValues("No")],
    "NodeNo": [i[1] for i in Visum.Net.StopPoints.GetMultiAttValues("NodeNo")],
})
visum_stop_points = visum_stop_points.astype(int)
visum_stop_points

        No  NodeNo
0        1   85179
1        2   52849
2        3   52902
3        4   52904
4        5   53616
...    ...     ...
7369  7370   50803
7370  7371   51913
7371  7372   51958
7372  7373   83434
7373  7374   45360

[7374 rows x 2 columns]

### Join SP df with StopPointNo (ID) from Visum

In [18]:
stop_points = pd.merge(sp2024_withSequence, visum_stop_points, left_on="NODE", right_on="NodeNo", how="left")
stop_points = stop_points.rename(columns={"No": "StopPointNo"})

#Remove rows with missing values in SECUENCIA or DIR columns (45,342 paradas x ruta --> 43,774 paradas x ruta)
#From original stop points df csv 1,568 rows had missing values in SECUENCIA or DIR columns, which are necessary for assigning stop points to a line route. 
# These rows will be removed 
stop_points_cleaned = stop_points.dropna(subset=["SECUENCIA", "DIR"])
stop_points_cleaned = stop_points_cleaned.astype({"SECUENCIA": int, "DIR": int})
stop_points_cleaned

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO,StopPointNo,NodeNo
0,1,1,1,0.000000,1,0.0,1.0,1,120551.0,1,85179,Parada,1,85179
1,2,1,1,0.459851,2,459.0,1.0,2,140696.0,1,52849,Parada,2,52849
2,3,1,1,0.646481,3,646.0,1.0,5,79908.0,-1,52902,Parada,3,52902
3,4,1,1,0.872291,4,872.0,1.0,7,79910.0,-1,52904,Parada,4,52904
4,5,1,1,1.219899,5,1219.0,1.0,9,144971.0,1,53616,Parada,5,53616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,46313,1337,1,8.795644,46313,21423.0,521.0,204,66298.0,-1,1797,Parada,6378,1797
43770,46314,1337,1,9.013195,46314,21640.0,521.0,210,117476.0,-1,82302,Parada,6387,82302
43771,46315,1337,1,9.230524,46315,21858.0,521.0,215,66355.0,-1,44351,Parada,6388,44351
43772,46316,1337,1,9.652481,46316,22280.0,521.0,218,66358.0,-1,44333,Parada,6389,44333
43773,46318,1337,1,0.281257,46318,12929.0,521.0,123,118927.0,1,45360,Parada,7374,45360

## Read LineRoutes CSV (rutas publicas insumo de IMEPLAN)

In [89]:
#csv puntos parada 2024
ro2024_csv = r"C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Transporte Publico\Rutas Operando\RutasOperando2024_Attributes.csv"
ro2024_df = pd.read_csv(ro2024_csv)
ro2024_df

,ROUTE_ID,ROUTE_NAME,ID_RUTA,TIME,LONGITUD,DISTANCE,RUTA_ACT,RUTA_ANT,CLASE,ORI_DES,...,FLOTA,CAPACIDAD,HEADWAY,TDR,MODE,CORREDOR,DEMANDA1,DEMANDA2,DEMANDA3,F_CORREDOR
0,1,Route 1,1,36.05,9.55,0.0,C33 Via Corta,NaN,Complementarias,NaN,...,0.0,240.0,20.0,31.63,1,NaN,0.0,0.0,0.00,0.0000
1,2,Route 10,10,68.46,16.93,0.0,C02,45A_2,Complementarias,Destino:�Centro Metropolitano,...,17.0,536.0,9.0,60.07,1,NaN,0.0,0.0,0.00,0.0000
2,3,Route 100,100,116.25,39.28,3874.0,C125 Valle de los Emperadores,186 Valle de los Emperadores_2,Complementarias,Destino: Antigua Central de Autobuses,...,29.0,404.2,14.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
3,4,Route 101,101,114.35,38.50,3904.0,C125 Valle de los Emperadores directa,186 Valle de los Emperadores - Direct_1,Complementarias,Origen: Valle de los Emperadores,...,21.0,297.0,18.0,120.11,1,11.0,0.0,0.0,3.16,101.4041
4,5,Route 102,102,116.25,39.28,3874.0,C125 Valle de los Emperadores directa,186 Valle de los Emperadores - Direct_2,Complementarias,Destino: Antigua Central de Autobuses,...,21.0,297.0,18.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,1333,Route 952,952,69.92,17.35,0.0,L3 Alimentadora Milpillas Op3,L3,SITREN,Milpillas,...,5.0,112.0,20.0,81.21,6,10.0,0.0,0.0,0.00,0.0000
792,1334,Route 953,953,94.06,12.54,0.0,L3 Alimentadora Angeles Op3,L3,SITREN,�ngeles,...,9.0,152.0,20.0,86.09,6,NaN,0.0,0.0,0.00,0.0000
793,1335,Route 954,954,98.18,13.31,0.0,L3 Alimentadora Angeles Op3,L3,SITREN,�ngeles,...,9.0,152.0,20.0,89.98,6,NaN,0.0,0.0,0.00,0.0000
794,1336,Route 955,955,83.77,9.64,0.0,L3 Alimentadora Las Agujas Op3,L3,SITREN,T16B-C03,...,20.0,440.0,12.0,76.86,6,NaN,0.0,0.0,0.00,0.0000
795,1337,Route 956,956,81.96,9.67,0.0,L3 Alimentadora Las Agujas Op3,L3,SITREN,T16B-C03,...,20.0,440.0,12.0,75.44,6,NaN,0.0,0.0,0.00,0.0000

### __que haces con las rutas repetidas que se supone una es de ida y otra de regreso pero por ejemplo la 1003 y 1004 son exactamente la misma tiene los mismos NODES en la misma seq. con las mismas direcciones PERO NO PUEDES SABER QUE ES LA MISMA RUTA PORQUE TIENE DIFERENTE ROUTE_ID solo lo sabrias si ves sus elementos

In [26]:
sp2024_withSequence[sp2024_withSequence['ROUTE_ID'] == 1003]

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
2853,2854,1003,1,0.190977,2854,190.0,135.0,1.0,145013.0,-1.0,105863,Parada
2854,2855,1003,1,0.376770,2855,376.0,135.0,3.0,126321.0,1.0,102391,Parada
2855,2856,1003,1,0.762895,2856,762.0,135.0,5.0,126322.0,1.0,105865,Parada
2856,2857,1003,1,1.523722,2857,1523.0,135.0,16.0,77366.0,1.0,51118,Parada
2857,2858,1003,1,1.723795,2858,1723.0,135.0,20.0,77078.0,-1.0,51122,Parada
2858,2859,1003,1,1.938552,2859,1938.0,135.0,25.0,77082.0,1.0,51126,Parada
2859,2860,1003,1,2.115774,2860,2115.0,135.0,27.0,77080.0,1.0,51125,Parada
2860,2861,1003,1,2.371477,2861,2371.0,135.0,29.0,88846.0,1.0,105862,Parada
2861,2862,1003,1,2.788811,2862,2788.0,135.0,31.0,88847.0,1.0,9084,Parada
2862,2863,1003,1,3.125591,2863,3125.0,135.0,34.0,86886.0,1.0,56959,Parada
2863,2864,1003,1,4.060054,2864,4060.0,135.0,37.0,144932.0,-1.0,105782,Parada
2864,2865,1003,1,8.082911,2865,8082.0,135.0,56.0,120218.0,-1.0,52149,Parada
2865,2866,1003,1,8.519498,2866,8519.0,135.0,58.0,144988.0,-1.0,105838,Parada
2866,2867,1003,1,8.706283,2867,8706.0,135.0,59.0,75214.0,-1.0,49827,Parada
2867,2868,1003,1,9.120179,2868,9120.0,135.0,62.0,75217.0,-1.0,49975,Parada
2868,2869,1003,1,9.426425,2869,9426.0,135.0,66.0,75103.0,1.0,49746,Parada
2869,2870,1003,1,9.636150,2870,9636.0,135.0,69.0,75037.0,1.0,49855,Parada
2870,2871,1003,1,9.923424,2871,9923.0,135.0,72.0,75053.0,1.0,49767,Parada
2871,2872,1003,1,10.238880,2872,10238.0,135.0,73.0,74929.0,1.0,59958,Parada
2872,2873,1003,1,10.587556,2873,10587.0,135.0,75.0,97358.0,1.0,105837,Parada
2873,2874,1003,1,10.775743,2874,10775.0,135.0,78.0,97219.0,1.0,65032,Parada
2874,2875,1003,1,11.577144,2875,11577.0,135.0,82.0,97213.0,1.0,65030,Parada
2875,2876,1003,1,12.597648,2876,12597.0,135.0,85.0,126243.0,1.0,90402,Parada
2876,2877,1003,1,13.289207,2877,13289.0,135.0,90.0,126238.0,-1.0,90397,Parada
2877,2878,1003,1,13.480645,2878,13480.0,135.0,92.0,97321.0,1.0,65126,Parada
2878,2879,1003,1,14.342443,2879,14342.0,135.0,96.0,119612.0,1.0,84260,Parada
2879,2880,1003,1,14.602062,2880,14602.0,135.0,97.0,137827.0,1.0,99993,Parada
2880,2881,1003,1,15.675946,2881,15675.0,135.0,98.0,137828.0,1.0,84240,Parada
2881,2882,1003,1,16.206089,2882,16206.0,135.0,102.0,132616.0,1.0,65194,Parada
2882,2883,1003,1,16.755455,2883,16755.0,135.0,107.0,97420.0,-1.0,102590,Parada
2883,2884,1003,1,17.115850,2884,17115.0,135.0,111.0,74699.0,-1.0,48328,Parada
2884,2885,1003,1,17.567669,2885,17567.0,135.0,115.0,72803.0,-1.0,48337,Parada
2885,2886,1003,1,17.801924,2886,17801.0,135.0,117.0,72808.0,-1.0,48340,Parada
2886,2887,1003,1,18.055117,2887,18055.0,135.0,119.0,72810.0,-1.0,48342,Parada
2887,2888,1003,1,18.252348,2888,18252.0,135.0,120.0,72815.0,-1.0,48345,Parada
2888,2889,1003,1,18.445511,2889,18445.0,135.0,121.0,72816.0,-1.0,48312,Parada
2889,2890,1003,1,18.786089,2890,18786.0,135.0,125.0,72818.0,-1.0,48348,Parada
2890,2891,1003,1,19.039215,2891,19039.0,135.0,126.0,72869.0,1.0,48388,Parada
2891,2892,1003,1,19.297924,2892,19297.0,135.0,127.0,72888.0,-1.0,48394,Parada
2892,2893,1003,1,19.550407,2893,19550.0,135.0,128.0,72894.0,-1.0,48401,Parada
2893,2894,1003,1,19.811306,2894,19811.0,135.0,129.0,72902.0,1.0,48406,Parada
2894,2895,1003,1,20.092472,2895,20092.0,135.0,133.0,72932.0,-1.0,48425,Parada
2895,2896,1003,1,20.317621,2896,20317.0,135.0,135.0,72991.0,-1.0,48427,Parada
2896,2897,1003,1,20.957245,2897,20957.0,135.0,141.0,73042.0,-1.0,48502,Parada
2897,2898,1003,1,21.308657,2898,21308.0,135.0,145.0,73131.0,-1.0,48581,Parada
2898,2899,1003,1,21.937479,2899,21937.0,135.0,149.0,97318.0,-1.0,65127,Parada
2899,2900,1003,1,22.479645,2900,22479.0,135.0,150.0,97317.0,-1.0,65126,Parada
2901,2902,1003,1,25.266182,2902,25266.0,135.0,160.0,97211.0,-1.0,65507,Parada
2917,2918,1003,1,34.212772,2918,34212.0,135.0,215.0,88850.0,-1.0,58202,Parada

In [25]:
sp2024_withSequence[sp2024_withSequence['ROUTE_ID'] == 1004]

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
2918,2919,1004,1,0.190977,2919,190.0,136.0,1.0,145013.0,-1.0,105863,Parada
2919,2920,1004,1,0.376770,2920,376.0,136.0,3.0,126321.0,1.0,102391,Parada
2920,2921,1004,1,0.762895,2921,762.0,136.0,5.0,126322.0,1.0,105865,Parada
2921,2922,1004,1,1.523722,2922,1523.0,136.0,16.0,77366.0,1.0,51118,Parada
2922,2923,1004,1,1.723795,2923,1723.0,136.0,20.0,77078.0,-1.0,51122,Parada
2923,2924,1004,1,1.938552,2924,1938.0,136.0,25.0,77082.0,1.0,51126,Parada
2924,2925,1004,1,2.115774,2925,2115.0,136.0,27.0,77080.0,1.0,51125,Parada
2925,2926,1004,1,2.371477,2926,2371.0,136.0,29.0,88846.0,1.0,105862,Parada
2926,2927,1004,1,2.788811,2927,2788.0,136.0,31.0,88847.0,1.0,9084,Parada
2927,2928,1004,1,3.125591,2928,3125.0,136.0,34.0,86886.0,1.0,56959,Parada
2928,2929,1004,1,4.060054,2929,4060.0,136.0,37.0,144932.0,-1.0,105782,Parada
2929,2930,1004,1,8.082911,2930,8082.0,136.0,56.0,120218.0,-1.0,52149,Parada
2930,2931,1004,1,8.519498,2931,8519.0,136.0,58.0,144988.0,-1.0,105838,Parada
2931,2932,1004,1,8.706283,2932,8706.0,136.0,59.0,75214.0,-1.0,49827,Parada
2932,2933,1004,1,9.120179,2933,9120.0,136.0,62.0,75217.0,-1.0,49975,Parada
2933,2934,1004,1,9.426425,2934,9426.0,136.0,66.0,75103.0,1.0,49746,Parada
2934,2935,1004,1,9.636150,2935,9636.0,136.0,69.0,75037.0,1.0,49855,Parada
2935,2936,1004,1,9.923424,2936,9923.0,136.0,72.0,75053.0,1.0,49767,Parada
2936,2937,1004,1,10.238880,2937,10238.0,136.0,73.0,74929.0,1.0,59958,Parada
2937,2938,1004,1,10.587556,2938,10587.0,136.0,75.0,97358.0,1.0,105837,Parada
2938,2939,1004,1,10.775743,2939,10775.0,136.0,78.0,97219.0,1.0,65032,Parada
2939,2940,1004,1,11.577144,2940,11577.0,136.0,82.0,97213.0,1.0,65030,Parada
2940,2941,1004,1,12.597648,2941,12597.0,136.0,85.0,126243.0,1.0,90402,Parada
2941,2942,1004,1,13.289207,2942,13289.0,136.0,90.0,126238.0,-1.0,90397,Parada
2942,2943,1004,1,13.480645,2943,13480.0,136.0,92.0,97321.0,1.0,65126,Parada
2943,2944,1004,1,14.022811,2944,14022.0,136.0,93.0,97317.0,1.0,65127,Parada
2944,2945,1004,1,14.519076,2945,14519.0,136.0,95.0,97359.0,1.0,65147,Parada
2945,2946,1004,1,14.915170,2946,14915.0,136.0,100.0,73117.0,1.0,48517,Parada
2946,2947,1004,1,15.642668,2947,15642.0,136.0,107.0,72992.0,1.0,48427,Parada
2947,2948,1004,1,15.867817,2948,15867.0,136.0,109.0,72972.0,1.0,48425,Parada
2948,2949,1004,1,16.148983,2949,16148.0,136.0,113.0,72911.0,1.0,48406,Parada
2949,2950,1004,1,16.409882,2950,16409.0,136.0,114.0,72902.0,-1.0,48401,Parada
2950,2951,1004,1,16.662365,2951,16662.0,136.0,115.0,72894.0,1.0,48394,Parada
2951,2952,1004,1,16.921074,2952,16921.0,136.0,116.0,72888.0,1.0,48388,Parada
2952,2953,1004,1,17.174200,2953,17174.0,136.0,117.0,72869.0,-1.0,48348,Parada
2953,2954,1004,1,17.436842,2954,17436.0,136.0,120.0,72866.0,-1.0,48382,Parada
2954,2955,1004,1,17.707941,2955,17707.0,136.0,122.0,72816.0,1.0,48345,Parada
2955,2956,1004,1,17.905172,2956,17905.0,136.0,123.0,72815.0,1.0,48342,Parada
2956,2957,1004,1,18.158365,2957,18158.0,136.0,125.0,72809.0,1.0,48340,Parada
2957,2958,1004,1,18.392620,2958,18392.0,136.0,127.0,72807.0,1.0,48337,Parada
2958,2959,1004,1,18.685305,2959,18685.0,136.0,129.0,72797.0,1.0,48330,Parada
2959,2960,1004,1,19.204834,2960,19204.0,136.0,135.0,97430.0,1.0,102590,Parada
2960,2961,1004,1,19.767302,2961,19767.0,136.0,142.0,97419.0,1.0,65189,Parada
2961,2962,1004,1,20.303162,2962,20303.0,136.0,144.0,119729.0,1.0,84240,Parada
2962,2963,1004,1,21.377045,2963,21377.0,136.0,145.0,137828.0,-1.0,99993,Parada
2963,2964,1004,1,21.636665,2964,21636.0,136.0,146.0,137827.0,-1.0,84260,Parada
2964,2965,1004,1,22.480045,2965,22480.0,136.0,149.0,97320.0,1.0,65088,Parada
2965,2966,1004,1,25.136353,2966,25136.0,136.0,156.0,97211.0,-1.0,65507,Parada
2981,2982,1004,1,34.082943,2982,34082.0,136.0,211.0,88850.0,-1.0,58202,Parada

### Cantidad de rutas originales(incluyendo las que tienen todas sus paradas SIN SECUENCIA) y rutas finales donde sus paradas SI TIENEN SECUENCIA

In [78]:
#42 rutas tenian todas sus paradas SIN SECUENCIA, Y NO ERAN USABLES
print(f'Total routes in ro2024_df: {ro2024_df["ROUTE_ID"].nunique()}')
print(f'Total routes with SEQUENCE on their stop points: {stop_points_cleaned["ROUTE_ID"].nunique()}')

Total routes in ro2024_df: 796
Total routes with SEQUENCE on their stop points: 754

## Create LINE ROUTES

### __Define search parameters__

#### __HowToHandleIncompleteRoute__
* RouteSearchHandleIncompleteRouteTIgnoreLine = 0
* RouteSearchHandleIncompleteRouteTInsertLink = 1
* RouteSearchHandleIncompleteRouteTOpenLink = 4
* RouteSearchHandleIncompleteRouteTSearchShortestPath = 2 __(uses this)__
* RouteSearchHandleIncompleteRouteTSearchShortestPath = 3

#### __ShortestPathCriterion__
* ShortestPathCriterion_LinkLength = 3 Link Length
* ShortestPathCriterion_LinkLengthDir = 0 Link Direct Distance __(changed it to this)__
* ShortestPathCriterion_LinkT_Sys = 1 Link travel time of current transport system __(this as default but i dont have travel times yet)__
* ShortestPathCriterion_LinktypeT_Sys = 2 Link type travel time of current transport system

#### __WhatToDoIfShortestPathNotFound__
* IfNotFound_DontRead = 0 Do not read __(this as default)__
* IfNotFound_InsertLink = 2 Insert link if necessary
* IfNotFound_OpenLink = 1 Open link or turn for transport system __(changed it to this)__

In [79]:
#Route search params
route_search_params = Visum.IO.CreateNetReadRouteSearchTSys()
route_search_params.SetAttValue("HowToHandleIncompleteRoute", C.RouteSearchHandleIncompleteRouteTSearchShortestPath) #2 RouteSearchHandleIncompleteRouteTSearchShortestPath
route_search_params.SetAttValue("ShortestPathCriterion", C.ShortestPathCriterion_LinkT_Sys) #1 ShortestPathCriterion_LinkT_Sys = link travel time of current transport system
route_search_params.SetAttValue("IncludeBlockedLinks", False)
route_search_params.SetAttValue("IncludeBlockedTurns", False)
route_search_params.SetAttValue("MaxDeviationFactor", 1000)
route_search_params.SetAttValue("WhatToDoIfShortestPathNotFound", 0)

In [91]:
ro2024_df

,ROUTE_ID,ROUTE_NAME,ID_RUTA,TIME,LONGITUD,DISTANCE,RUTA_ACT,RUTA_ANT,CLASE,ORI_DES,...,FLOTA,CAPACIDAD,HEADWAY,TDR,MODE,CORREDOR,DEMANDA1,DEMANDA2,DEMANDA3,F_CORREDOR
0,1,Route 1,1,36.05,9.55,0.0,C33 Via Corta,NaN,Complementarias,NaN,...,0.0,240.0,20.0,31.63,1,NaN,0.0,0.0,0.00,0.0000
1,2,Route 10,10,68.46,16.93,0.0,C02,45A_2,Complementarias,Destino:�Centro Metropolitano,...,17.0,536.0,9.0,60.07,1,NaN,0.0,0.0,0.00,0.0000
2,3,Route 100,100,116.25,39.28,3874.0,C125 Valle de los Emperadores,186 Valle de los Emperadores_2,Complementarias,Destino: Antigua Central de Autobuses,...,29.0,404.2,14.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
3,4,Route 101,101,114.35,38.50,3904.0,C125 Valle de los Emperadores directa,186 Valle de los Emperadores - Direct_1,Complementarias,Origen: Valle de los Emperadores,...,21.0,297.0,18.0,120.11,1,11.0,0.0,0.0,3.16,101.4041
4,5,Route 102,102,116.25,39.28,3874.0,C125 Valle de los Emperadores directa,186 Valle de los Emperadores - Direct_2,Complementarias,Destino: Antigua Central de Autobuses,...,21.0,297.0,18.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,1333,Route 952,952,69.92,17.35,0.0,L3 Alimentadora Milpillas Op3,L3,SITREN,Milpillas,...,5.0,112.0,20.0,81.21,6,10.0,0.0,0.0,0.00,0.0000
792,1334,Route 953,953,94.06,12.54,0.0,L3 Alimentadora Angeles Op3,L3,SITREN,�ngeles,...,9.0,152.0,20.0,86.09,6,NaN,0.0,0.0,0.00,0.0000
793,1335,Route 954,954,98.18,13.31,0.0,L3 Alimentadora Angeles Op3,L3,SITREN,�ngeles,...,9.0,152.0,20.0,89.98,6,NaN,0.0,0.0,0.00,0.0000
794,1336,Route 955,955,83.77,9.64,0.0,L3 Alimentadora Las Agujas Op3,L3,SITREN,T16B-C03,...,20.0,440.0,12.0,76.86,6,NaN,0.0,0.0,0.00,0.0000
795,1337,Route 956,956,81.96,9.67,0.0,L3 Alimentadora Las Agujas Op3,L3,SITREN,T16B-C03,...,20.0,440.0,12.0,75.44,6,NaN,0.0,0.0,0.00,0.0000

In [81]:
ro2024_df = ro2024_df.sort_values(by='ROUTE_ID')

In [56]:
route_stop_points = stop_points_cleaned[stop_points_cleaned['ROUTE_ID'] == 175]
route_stop_points

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO,StopPointNo,NodeNo
10795,10915,175,1,0.306602,10915,306.0,256.0,4,46153.0,1,32861,Parada,3921,32861
10796,10916,175,1,0.514242,10916,514.0,256.0,6,46416.0,1,32828,Parada,3922,32828
10797,10917,175,1,0.867302,10917,867.0,256.0,12,46046.0,1,32847,Parada,3923,32847
10798,10918,175,1,1.154116,10918,1154.0,256.0,16,46042.0,1,32841,Parada,3924,32841
10799,10919,175,1,1.447206,10919,1447.0,256.0,17,46041.0,1,32843,Parada,3925,32843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10855,10975,175,1,16.696772,10975,16696.0,256.0,184,35747.0,-1,26532,Parada,517,26532
10856,10976,175,1,17.051222,10976,17051.0,256.0,187,35569.0,-1,26535,Parada,502,26535
10857,10977,175,1,17.320377,10977,17320.0,256.0,190,35837.0,-1,26514,Parada,3947,26514
10858,10978,175,1,17.513462,10978,17513.0,256.0,193,35840.0,-1,26497,Parada,1315,26497
10859,10979,175,1,17.842918,10979,17842.0,256.0,197,35844.0,-1,25862,Parada,1831,25862

In [82]:
line_no = 1

for row in ro2024_df.itertuples():
    route_id = row.ROUTE_ID
    route_name_ID = row.ID_RUTA

    #Check if route_id exists in stop_points_cleaned ROUTE_ID column, if not skip to next iteration
    if(stop_points_cleaned.loc[stop_points_cleaned['ROUTE_ID'] == route_id].empty):
        print(f"Route ID {route_id} not found in stop points dataframe.")
        continue

     #Create line
    tsys_bus = Net.TSystems.ItemByKey("B")
    line = Net.AddLine('Line ' + str(route_id), tsys_bus)

    #Direction
    direction = Visum.Net.Directions.GetAll[0]

    #Get stop points for route_id
    route_stop_points = stop_points_cleaned[stop_points_cleaned['ROUTE_ID'] == route_id]

    #Sort by SECUENCIA column to ensure correct order of stop points in line route
    route_stop_points = route_stop_points.sort_values(by='SECUENCIA')

    #Create collection of stop points for line route
    route_elements = Visum.CreateNetElements()

    #Add stop points to route elements collection
    for row in route_stop_points.itertuples():
        stop_point_no = row.StopPointNo
        sp = Net.StopPoints.ItemByKey(stop_point_no)
        route_elements.Add(sp)

    #Create line route
    print('creating line route with ROUTE_ID', route_id)
    try:
        line_route = Net.AddLineRoute('LineRoute ' + str(route_id), line, direction, route_elements, route_search_params)
        if line_route is None:
            print(f"⚠️ No se pudo crear LineRoute para Route ID {route_id}: ruta no encontrada, ignorando.")
            continue
        print(f"✅ LineRoute creada para Route ID {route_id}")
    except Exception as e:
        print(f"⚠️ Error al crear LineRoute para Route ID {route_id}: {e}, ignorando.")
        continue

creating line route with ROUTE_ID 1
✅ LineRoute creada para Route ID 1
creating line route with ROUTE_ID 2
✅ LineRoute creada para Route ID 2
creating line route with ROUTE_ID 3
✅ LineRoute creada para Route ID 3
creating line route with ROUTE_ID 4
✅ LineRoute creada para Route ID 4
creating line route with ROUTE_ID 5
✅ LineRoute creada para Route ID 5
creating line route with ROUTE_ID 10
✅ LineRoute creada para Route ID 10
creating line route with ROUTE_ID 11
✅ LineRoute creada para Route ID 11
creating line route with ROUTE_ID 13
✅ LineRoute creada para Route ID 13
creating line route with ROUTE_ID 15
✅ LineRoute creada para Route ID 15
creating line route with ROUTE_ID 16
✅ LineRoute creada para Route ID 16
creating line route with ROUTE_ID 17
✅ LineRoute creada para Route ID 17
creating line route with ROUTE_ID 18
✅ LineRoute creada para Route ID 18
creating line route with ROUTE_ID 19
✅ LineRoute creada para Route ID 19
creating line route with ROUTE_ID 20
✅ LineRoute creada para Route ID 20
creating line route with ROUTE_ID 21
✅ LineRoute creada para Route ID 21
creating line route with ROUTE_ID 22
✅ LineRoute creada para Route ID 22
creating line route with ROUTE_ID 23
✅ LineRoute creada para Route ID 23
creating line route with ROUTE_ID 24
✅ LineRoute creada para Route ID 24
creating line route with ROUTE_ID 25
✅ LineRoute creada para Route ID 25
creating line route with ROUTE_ID 26
✅ LineRoute creada para Route ID 26
creating line route with ROUTE_ID 27
✅ LineRoute creada para Route ID 27
creating line route with ROUTE_ID 34
✅ LineRoute creada para Route ID 34
creating line route with ROUTE_ID 36
✅ LineRoute creada para Route ID 36
creating line route with ROUTE_ID 37
✅ LineRoute creada para Route ID 37
creating line route with ROUTE_ID 38
✅ LineRoute creada para Route ID 38
creating line route with ROUTE_ID 45
✅ LineRoute creada para Route ID 45
creating line route with ROUTE_ID 46
✅ LineRoute creada para Route ID 46
creating line route with ROUTE_ID 47
✅ LineRoute creada para Route ID 47
creating line route with ROUTE_ID 48
✅ LineRoute creada para Route ID 48
creating line route with ROUTE_ID 49
✅ LineRoute creada para Route ID 49
creating line route with ROUTE_ID 50
✅ LineRoute creada para Route ID 50
creating line route with ROUTE_ID 51
✅ LineRoute creada para Route ID 51
creating line route with ROUTE_ID 52
✅ LineRoute creada para Route ID 52
creating line route with ROUTE_ID 53
✅ LineRoute creada para Route ID 53
creating line route with ROUTE_ID 54
✅ LineRoute creada para Route ID 54
creating line route with ROUTE_ID 55
✅ LineRoute creada para Route ID 55
creating line route with ROUTE_ID 56
✅ LineRoute creada para Route ID 56
creating line route with ROUTE_ID 58
✅ LineRoute creada para Route ID 58
creating line route with ROUTE_ID 59
✅ LineRoute creada para Route ID 59
creating line route with ROUTE_ID 60
✅ LineRoute creada para Route ID 60
creating line route with ROUTE_ID 61
✅ LineRoute creada para Route ID 61
creating line route with ROUTE_ID 62
✅ LineRoute creada para Route ID 62
creating line route with ROUTE_ID 63
✅ LineRoute creada para Route ID 63
creating line route with ROUTE_ID 64
✅ LineRoute creada para Route ID 64
creating line route with ROUTE_ID 65
✅ LineRoute creada para Route ID 65
creating line route with ROUTE_ID 66
✅ LineRoute creada para Route ID 66
creating line route with ROUTE_ID 67
✅ LineRoute creada para Route ID 67
creating line route with ROUTE_ID 69
✅ LineRoute creada para Route ID 69
creating line route with ROUTE_ID 70
✅ LineRoute creada para Route ID 70
creating line route with ROUTE_ID 71
✅ LineRoute creada para Route ID 71
creating line route with ROUTE_ID 72
✅ LineRoute creada para Route ID 72
creating line route with ROUTE_ID 73
✅ LineRoute creada para Route ID 73
creating line route with ROUTE_ID 74
✅ LineRoute creada para Route ID 74
creating line route with ROUTE_ID 75
✅ LineRoute creada para Route ID 75
creating line route with ROUTE_ID 76
✅ LineRoute creada para Route ID 76
creating line route with ROUTE_ID 77
✅ LineRoute creada para Route ID 77
creating line route with ROUTE_ID 78
✅ LineRoute creada para Route ID 78
creating line route with ROUTE_ID 79
✅ LineRoute creada para Route ID 79
creating line route with ROUTE_ID 80
✅ LineRoute creada para Route ID 80
creating line route with ROUTE_ID 81
✅ LineRoute creada para Route ID 81
creating line route with ROUTE_ID 82
✅ LineRoute creada para Route ID 82
creating line route with ROUTE_ID 83
✅ LineRoute creada para Route ID 83
creating line route with ROUTE_ID 84
✅ LineRoute creada para Route ID 84
creating line route with ROUTE_ID 85
✅ LineRoute creada para Route ID 85
creating line route with ROUTE_ID 86
✅ LineRoute creada para Route ID 86
creating line route with ROUTE_ID 87
✅ LineRoute creada para Route ID 87
creating line route with ROUTE_ID 88
✅ LineRoute creada para Route ID 88
creating line route with ROUTE_ID 89
✅ LineRoute creada para Route ID 89
creating line route with ROUTE_ID 90
✅ LineRoute creada para Route ID 90
creating line route with ROUTE_ID 91
✅ LineRoute creada para Route ID 91
creating line route with ROUTE_ID 92
✅ LineRoute creada para Route ID 92
creating line route with ROUTE_ID 93
✅ LineRoute creada para Route ID 93
creating line route with ROUTE_ID 94
✅ LineRoute creada para Route ID 94
creating line route with ROUTE_ID 95
✅ LineRoute creada para Route ID 95
creating line route with ROUTE_ID 96
✅ LineRoute creada para Route ID 96
creating line route with ROUTE_ID 97
✅ LineRoute creada para Route ID 97
creating line route with ROUTE_ID 98
✅ LineRoute creada para Route ID 98
creating line route with ROUTE_ID 99
✅ LineRoute creada para Route ID 99
creating line route with ROUTE_ID 100
✅ LineRoute creada para Route ID 100
creating line route with ROUTE_ID 101
✅ LineRoute creada para Route ID 101
creating line route with ROUTE_ID 102
✅ LineRoute creada para Route ID 102
creating line route with ROUTE_ID 103
✅ LineRoute creada para Route ID 103
creating line route with ROUTE_ID 104
✅ LineRoute creada para Route ID 104
creating line route with ROUTE_ID 111
✅ LineRoute creada para Route ID 111
creating line route with ROUTE_ID 112
✅ LineRoute creada para Route ID 112
creating line route with ROUTE_ID 113
✅ LineRoute creada para Route ID 113
creating line route with ROUTE_ID 114
✅ LineRoute creada para Route ID 114
creating line route with ROUTE_ID 118
✅ LineRoute creada para Route ID 118
creating line route with ROUTE_ID 119
✅ LineRoute creada para Route ID 119
creating line route with ROUTE_ID 121
✅ LineRoute creada para Route ID 121
creating line route with ROUTE_ID 122
✅ LineRoute creada para Route ID 122
creating line route with ROUTE_ID 123
✅ LineRoute creada para Route ID 123
creating line route with ROUTE_ID 124
✅ LineRoute creada para Route ID 124
creating line route with ROUTE_ID 128
✅ LineRoute creada para Route ID 128
creating line route with ROUTE_ID 129
✅ LineRoute creada para Route ID 129
creating line route with ROUTE_ID 130
✅ LineRoute creada para Route ID 130
creating line route with ROUTE_ID 131
✅ LineRoute creada para Route ID 131
creating line route with ROUTE_ID 132
✅ LineRoute creada para Route ID 132
creating line route with ROUTE_ID 133
✅ LineRoute creada para Route ID 133
creating line route with ROUTE_ID 134
✅ LineRoute creada para Route ID 134
creating line route with ROUTE_ID 135
✅ LineRoute creada para Route ID 135
creating line route with ROUTE_ID 136
✅ LineRoute creada para Route ID 136
creating line route with ROUTE_ID 137
✅ LineRoute creada para Route ID 137
creating line route with ROUTE_ID 138
✅ LineRoute creada para Route ID 138
creating line route with ROUTE_ID 139
✅ LineRoute creada para Route ID 139
creating line route with ROUTE_ID 140
✅ LineRoute creada para Route ID 140
creating line route with ROUTE_ID 141
✅ LineRoute creada para Route ID 141
creating line route with ROUTE_ID 142
✅ LineRoute creada para Route ID 142
creating line route with ROUTE_ID 146
✅ LineRoute creada para Route ID 146
creating line route with ROUTE_ID 149
✅ LineRoute creada para Route ID 149
creating line route with ROUTE_ID 150
✅ LineRoute creada para Route ID 150
creating line route with ROUTE_ID 151
✅ LineRoute creada para Route ID 151
creating line route with ROUTE_ID 152
✅ LineRoute creada para Route ID 152
creating line route with ROUTE_ID 153
✅ LineRoute creada para Route ID 153
creating line route with ROUTE_ID 154
✅ LineRoute creada para Route ID 154
creating line route with ROUTE_ID 155
✅ LineRoute creada para Route ID 155
creating line route with ROUTE_ID 156
✅ LineRoute creada para Route ID 156
creating line route with ROUTE_ID 157
✅ LineRoute creada para Route ID 157
creating line route with ROUTE_ID 158
✅ LineRoute creada para Route ID 158
creating line route with ROUTE_ID 159
✅ LineRoute creada para Route ID 159
creating line route with ROUTE_ID 160
✅ LineRoute creada para Route ID 160
creating line route with ROUTE_ID 161
✅ LineRoute creada para Route ID 161
creating line route with ROUTE_ID 162
✅ LineRoute creada para Route ID 162
creating line route with ROUTE_ID 163
✅ LineRoute creada para Route ID 163
creating line route with ROUTE_ID 164
✅ LineRoute creada para Route ID 164
creating line route with ROUTE_ID 165
✅ LineRoute creada para Route ID 165
creating line route with ROUTE_ID 166
✅ LineRoute creada para Route ID 166
creating line route with ROUTE_ID 167
✅ LineRoute creada para Route ID 167
creating line route with ROUTE_ID 168
✅ LineRoute creada para Route ID 168
creating line route with ROUTE_ID 169
✅ LineRoute creada para Route ID 169
creating line route with ROUTE_ID 170
✅ LineRoute creada para Route ID 170
creating line route with ROUTE_ID 171
✅ LineRoute creada para Route ID 171
creating line route with ROUTE_ID 172
✅ LineRoute creada para Route ID 172
creating line route with ROUTE_ID 173
✅ LineRoute creada para Route ID 173
creating line route with ROUTE_ID 174
✅ LineRoute creada para Route ID 174
creating line route with ROUTE_ID 175
✅ LineRoute creada para Route ID 175
creating line route with ROUTE_ID 176
✅ LineRoute creada para Route ID 176
creating line route with ROUTE_ID 177
✅ LineRoute creada para Route ID 177
creating line route with ROUTE_ID 178
✅ LineRoute creada para Route ID 178
creating line route with ROUTE_ID 180
✅ LineRoute creada para Route ID 180
creating line route with ROUTE_ID 181
✅ LineRoute creada para Route ID 181
creating line route with ROUTE_ID 182
✅ LineRoute creada para Route ID 182
creating line route with ROUTE_ID 184
✅ LineRoute creada para Route ID 184
creating line route with ROUTE_ID 186
✅ LineRoute creada para Route ID 186
creating line route with ROUTE_ID 187
✅ LineRoute creada para Route ID 187
creating line route with ROUTE_ID 188
✅ LineRoute creada para Route ID 188
creating line route with ROUTE_ID 189
✅ LineRoute creada para Route ID 189
creating line route with ROUTE_ID 190
✅ LineRoute creada para Route ID 190
creating line route with ROUTE_ID 197
✅ LineRoute creada para Route ID 197
creating line route with ROUTE_ID 198
✅ LineRoute creada para Route ID 198
creating line route with ROUTE_ID 201
✅ LineRoute creada para Route ID 201
creating line route with ROUTE_ID 204
✅ LineRoute creada para Route ID 204
creating line route with ROUTE_ID 205
✅ LineRoute creada para Route ID 205
creating line route with ROUTE_ID 206
✅ LineRoute creada para Route ID 206
creating line route with ROUTE_ID 207
✅ LineRoute creada para Route ID 207
creating line route with ROUTE_ID 208
✅ LineRoute creada para Route ID 208
creating line route with ROUTE_ID 209
✅ LineRoute creada para Route ID 209
creating line route with ROUTE_ID 210
✅ LineRoute creada para Route ID 210
creating line route with ROUTE_ID 211
✅ LineRoute creada para Route ID 211
creating line route with ROUTE_ID 213
✅ LineRoute creada para Route ID 213
creating line route with ROUTE_ID 214
✅ LineRoute creada para Route ID 214
creating line route with ROUTE_ID 215
✅ LineRoute creada para Route ID 215
creating line route with ROUTE_ID 216
✅ LineRoute creada para Route ID 216
creating line route with ROUTE_ID 217
✅ LineRoute creada para Route ID 217
creating line route with ROUTE_ID 218
✅ LineRoute creada para Route ID 218
creating line route with ROUTE_ID 219
✅ LineRoute creada para Route ID 219
creating line route with ROUTE_ID 220
✅ LineRoute creada para Route ID 220
creating line route with ROUTE_ID 221
✅ LineRoute creada para Route ID 221
creating line route with ROUTE_ID 222
✅ LineRoute creada para Route ID 222
creating line route with ROUTE_ID 223
✅ LineRoute creada para Route ID 223
creating line route with ROUTE_ID 225
✅ LineRoute creada para Route ID 225
creating line route with ROUTE_ID 226
✅ LineRoute creada para Route ID 226
creating line route with ROUTE_ID 227
✅ LineRoute creada para Route ID 227
creating line route with ROUTE_ID 228
✅ LineRoute creada para Route ID 228
creating line route with ROUTE_ID 231
⚠️ Error al crear LineRoute para Route ID 231: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2501', 'CNet::AddLineRoute: Cannot evaluate route items', None, 0, -2147352567), None), ignorando.
creating line route with ROUTE_ID 232
✅ LineRoute creada para Route ID 232
creating line route with ROUTE_ID 240
✅ LineRoute creada para Route ID 240
creating line route with ROUTE_ID 241
✅ LineRoute creada para Route ID 241
creating line route with ROUTE_ID 242
✅ LineRoute creada para Route ID 242
creating line route with ROUTE_ID 243
✅ LineRoute creada para Route ID 243
creating line route with ROUTE_ID 245
✅ LineRoute creada para Route ID 245
creating line route with ROUTE_ID 248
✅ LineRoute creada para Route ID 248
creating line route with ROUTE_ID 249
✅ LineRoute creada para Route ID 249
creating line route with ROUTE_ID 253
✅ LineRoute creada para Route ID 253
creating line route with ROUTE_ID 254
✅ LineRoute creada para Route ID 254
creating line route with ROUTE_ID 255
✅ LineRoute creada para Route ID 255
creating line route with ROUTE_ID 256
✅ LineRoute creada para Route ID 256
creating line route with ROUTE_ID 258
✅ LineRoute creada para Route ID 258
creating line route with ROUTE_ID 259
✅ LineRoute creada para Route ID 259
creating line route with ROUTE_ID 260
✅ LineRoute creada para Route ID 260
creating line route with ROUTE_ID 261
✅ LineRoute creada para Route ID 261
creating line route with ROUTE_ID 262
✅ LineRoute creada para Route ID 262
creating line route with ROUTE_ID 263
✅ LineRoute creada para Route ID 263
creating line route with ROUTE_ID 264
✅ LineRoute creada para Route ID 264
creating line route with ROUTE_ID 265
✅ LineRoute creada para Route ID 265
creating line route with ROUTE_ID 266
✅ LineRoute creada para Route ID 266
creating line route with ROUTE_ID 267
✅ LineRoute creada para Route ID 267
creating line route with ROUTE_ID 269
✅ LineRoute creada para Route ID 269
creating line route with ROUTE_ID 270
✅ LineRoute creada para Route ID 270
creating line route with ROUTE_ID 273
✅ LineRoute creada para Route ID 273
creating line route with ROUTE_ID 274
✅ LineRoute creada para Route ID 274
creating line route with ROUTE_ID 275
✅ LineRoute creada para Route ID 275
creating line route with ROUTE_ID 276
✅ LineRoute creada para Route ID 276
creating line route with ROUTE_ID 277
✅ LineRoute creada para Route ID 277
creating line route with ROUTE_ID 278
✅ LineRoute creada para Route ID 278
creating line route with ROUTE_ID 280
✅ LineRoute creada para Route ID 280
creating line route with ROUTE_ID 281
✅ LineRoute creada para Route ID 281
creating line route with ROUTE_ID 282
✅ LineRoute creada para Route ID 282
creating line route with ROUTE_ID 283
✅ LineRoute creada para Route ID 283
creating line route with ROUTE_ID 284
✅ LineRoute creada para Route ID 284
creating line route with ROUTE_ID 285
✅ LineRoute creada para Route ID 285
creating line route with ROUTE_ID 286
✅ LineRoute creada para Route ID 286
creating line route with ROUTE_ID 287
⚠️ Error al crear LineRoute para Route ID 287: (-2147352567, 'Exception occurred.', (0, 'Visum.Visum.2501', 'CNet::AddLineRoute: Cannot evaluate route items', None, 0, -2147352567), None), ignorando.
creating line route with ROUTE_ID 288
✅ LineRoute creada para Route ID 288
creating line route with ROUTE_ID 289
✅ LineRoute creada para Route ID 289
creating line route with ROUTE_ID 291
✅ LineRoute creada para Route ID 291
creating line route with ROUTE_ID 292
✅ LineRoute creada para Route ID 292
creating line route with ROUTE_ID 293
✅ LineRoute creada para Route ID 293
creating line route with ROUTE_ID 294
✅ LineRoute creada para Route ID 294
creating line route with ROUTE_ID 295
✅ LineRoute creada para Route ID 295
creating line route with ROUTE_ID 296
✅ LineRoute creada para Route ID 296
creating line route with ROUTE_ID 297
✅ LineRoute creada para Route ID 297
creating line route with ROUTE_ID 298
✅ LineRoute creada para Route ID 298
creating line route with ROUTE_ID 300
✅ LineRoute creada para Route ID 300
creating line route with ROUTE_ID 304
✅ LineRoute creada para Route ID 304
creating line route with ROUTE_ID 305
✅ LineRoute creada para Route ID 305
creating line route with ROUTE_ID 306
✅ LineRoute creada para Route ID 306
creating line route with ROUTE_ID 307
✅ LineRoute creada para Route ID 307
creating line route with ROUTE_ID 308
✅ LineRoute creada para Route ID 308
creating line route with ROUTE_ID 309
✅ LineRoute creada para Route ID 309
creating line route with ROUTE_ID 313
✅ LineRoute creada para Route ID 313
creating line route with ROUTE_ID 314
✅ LineRoute creada para Route ID 314
creating line route with ROUTE_ID 323
✅ LineRoute creada para Route ID 323
creating line route with ROUTE_ID 324
✅ LineRoute creada para Route ID 324
creating line route with ROUTE_ID 325
✅ LineRoute creada para Route ID 325
creating line route with ROUTE_ID 334
✅ LineRoute creada para Route ID 334
creating line route with ROUTE_ID 335
✅ LineRoute creada para Route ID 335
creating line route with ROUTE_ID 338
✅ LineRoute creada para Route ID 338
creating line route with ROUTE_ID 339
✅ LineRoute creada para Route ID 339
creating line route with ROUTE_ID 342
✅ LineRoute creada para Route ID 342
creating line route with ROUTE_ID 343
✅ LineRoute creada para Route ID 343
creating line route with ROUTE_ID 344
✅ LineRoute creada para Route ID 344
creating line route with ROUTE_ID 345
✅ LineRoute creada para Route ID 345
creating line route with ROUTE_ID 346
✅ LineRoute creada para Route ID 346
creating line route with ROUTE_ID 347
✅ LineRoute creada para Route ID 347
creating line route with ROUTE_ID 348
✅ LineRoute creada para Route ID 348
creating line route with ROUTE_ID 349
✅ LineRoute creada para Route ID 349
creating line route with ROUTE_ID 350
✅ LineRoute creada para Route ID 350
creating line route with ROUTE_ID 353
✅ LineRoute creada para Route ID 353
creating line route with ROUTE_ID 354
✅ LineRoute creada para Route ID 354
creating line route with ROUTE_ID 355
✅ LineRoute creada para Route ID 355
creating line route with ROUTE_ID 356
✅ LineRoute creada para Route ID 356
creating line route with ROUTE_ID 357
✅ LineRoute creada para Route ID 357
creating line route with ROUTE_ID 358
✅ LineRoute creada para Route ID 358
creating line route with ROUTE_ID 359
✅ LineRoute creada para Route ID 359
creating line route with ROUTE_ID 360
✅ LineRoute creada para Route ID 360
creating line route with ROUTE_ID 361
✅ LineRoute creada para Route ID 361
creating line route with ROUTE_ID 362
✅ LineRoute creada para Route ID 362
creating line route with ROUTE_ID 363
✅ LineRoute creada para Route ID 363
creating line route with ROUTE_ID 364
✅ LineRoute creada para Route ID 364
creating line route with ROUTE_ID 365
✅ LineRoute creada para Route ID 365
creating line route with ROUTE_ID 366
✅ LineRoute creada para Route ID 366
creating line route with ROUTE_ID 367
✅ LineRoute creada para Route ID 367
creating line route with ROUTE_ID 368
✅ LineRoute creada para Route ID 368
creating line route with ROUTE_ID 369

### __comment__ cuando searchparameters usa LinkTsys las LineRoutes salen super extranas (y 4 no se pudieron generar no se por que). 

### __intentar mapear la LineRoute 1 solo para ver si si o no

In [86]:
sp_route1 = stop_points_cleaned[stop_points_cleaned['ROUTE_ID'] == 1]
tsys_bus = Net.TSystems.ItemByKey("B")
line1_test = Net.AddLine('Line1 Test', tsys_bus)

direction = Visum.Net.Directions.GetAll[0]

route_elements = Visum.CreateNetElements()
for row in sp_route1.itertuples():
    stop_point_no = row.StopPointNo
    sp = Net.StopPoints.ItemByKey(stop_point_no)
    route_elements.Add(sp)

search_params_linkTSys = Visum.IO.CreateNetReadRouteSearchTSys()
search_params_linkTSys.SetAttValue("HowToHandleIncompleteRoute", C.RouteSearchHandleIncompleteRouteTSearchShortestPath) #2 RouteSearchHandleIncompleteRouteTSearchShortestPath
search_params_linkTSys.SetAttValue("ShortestPathCriterion", 1) #1 ShortestPathCriterion_LinkT_Sys = link travel time of current transport system
search_params_linkTSys.SetAttValue("IncludeBlockedLinks", False)
search_params_linkTSys.SetAttValue("IncludeBlockedTurns", False)
search_params_linkTSys.SetAttValue("MaxDeviationFactor", 1000)
search_params_linkTSys.SetAttValue("WhatToDoIfShortestPathNotFound", 0)
line_route = Net.AddLineRoute('LineRoute1 TEST', line1_test, direction, route_elements, search_params_linkTSys)

In [106]:
sp2024_withSequence[sp2024_withSequence['ROUTE_ID'] == 3]

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
96,97,3,1,0.000000,97,0.0,100.0,1.0,57056.0,-1.0,38741,Parada
97,98,3,1,0.222721,98,222.0,100.0,2.0,145218.0,-1.0,106046,Parada
98,99,3,1,0.630473,99,630.0,100.0,4.0,57058.0,-1.0,26527,Parada
99,100,3,1,0.828130,100,828.0,100.0,6.0,88502.0,1.0,26472,Parada
100,101,3,1,1.038427,101,1038.0,100.0,8.0,35506.0,-1.0,26473,Parada
...,...,...,...,...,...,...,...,...,...,...,...,...
184,185,3,1,38.181557,185,38181.0,100.0,287.0,115114.0,1.0,80243,Parada
185,186,3,1,38.365906,186,38365.0,100.0,288.0,115115.0,1.0,80246,Parada
186,187,3,1,38.606274,187,38606.0,100.0,289.0,115116.0,1.0,80244,Parada
187,188,3,1,39.034855,188,39034.0,100.0,290.0,4613.0,1.0,4114,Parada
188,189,3,1,39.282646,189,39282.0,100.0,292.0,115171.0,-1.0,80305,Parada

In [107]:
no_sequence

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
41396,44753,3,1,35.385487,44753,NaN,NaN,NaN,NaN,NaN,4547,Extra
41395,44754,5,1,35.384651,44754,NaN,NaN,NaN,NaN,NaN,4547,Extra
41334,44759,10,1,7.386519,44759,NaN,NaN,NaN,NaN,NaN,98295,Extra
41333,44760,11,1,28.117382,44760,NaN,NaN,NaN,NaN,NaN,98295,Extra
44531,45387,215,1,3.226703,45387,NaN,NaN,NaN,NaN,NaN,72865,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
45230,46207,1333,1,0.032434,46207,NaN,NaN,NaN,NaN,NaN,83646,NaN
45286,46263,1335,1,0.034565,46263,NaN,NaN,NaN,NaN,NaN,83646,NaN
45287,46264,1335,1,0.570972,46264,NaN,NaN,NaN,NaN,NaN,83429,NaN
45313,46290,1336,1,9.784491,46290,NaN,NaN,NaN,NaN,NaN,83653,NaN
45340,46317,1337,1,0.042722,46317,NaN,NaN,NaN,NaN,NaN,45351,NaN

In [115]:
#get route_ids where some sp has no freq. but the rest of the route has sp
mostly_complete_routes = no_sequence[no_sequence['ROUTE_ID'].isin(sp2024_withSequence['ROUTE_ID'])]
mostly_complete_routesIDS = mostly_complete_routes['ROUTE_ID'].nunique()
usable_routes = ro2024_df[ro2024_df['ROUTE_ID'].isin(mostly_complete_routes['ROUTE_ID'])]

print(f'Unique values en SITUACION de rutas con algun SP sin SECUENCIA: {usable_routes['SITUACION'].unique()}')
print(f'Unique values en CLASE de rutas con algun SP sin SECUENCIA: {usable_routes['CLASE'].unique()}')
print(f'Total de rutas que tiene algun SP sin SECUENCIA pero aun se pueden formar: {len(usable_routes)}')
usable_routes.head()

Unique values en SITUACION de rutas con algun SP sin SECUENCIA: ['Operando' 'No opera' 'Operando*' 'Solo campo' 'Propuesta']
Unique values en CLASE de rutas con algun SP sin SECUENCIA: ['Complementarias' 'Alimentadora Macrob�s' 'Complementaria de troncal'
 'Troncal' 'Tren ligero' 'BRT' 'Alimentadora Mi Macro Perif�rico'
 'Complementaria Mi Macro Perif�rico' 'SITREN']
Total de rutas que tiene algun SP sin SECUENCIA pero aun se pueden formar: 149

,ROUTE_ID,ROUTE_NAME,ID_RUTA,TIME,LONGITUD,DISTANCE,RUTA_ACT,RUTA_ANT,CLASE,ORI_DES,...,FLOTA,CAPACIDAD,HEADWAY,TDR,MODE,CORREDOR,DEMANDA1,DEMANDA2,DEMANDA3,F_CORREDOR
2,3,Route 100,100,116.25,39.28,3874.0,C125 Valle de los Emperadores,186 Valle de los Emperadores_2,Complementarias,Destino: Antigua Central de Autobuses,...,29.0,404.2,14.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
4,5,Route 102,102,116.25,39.28,3874.0,C125 Valle de los Emperadores directa,186 Valle de los Emperadores - Direct_2,Complementarias,Destino: Antigua Central de Autobuses,...,21.0,297.0,18.0,121.80,1,11.0,0.0,0.0,2.07,98.6186
5,10,Route 107,107,119.10,35.73,2380.0,C127A (No Opera),183A Chulavista_1,Complementarias,Origen:�Villa Fontana Aqua Etapa 6,...,9.0,120.0,40.0,116.82,1,NaN,0.0,0.0,0.00,66.6106
6,11,Route 108,108,118.14,35.50,2055.0,C127A (No Opera),183A Chulavista_2,Complementarias,Destino: Rinconada del Bosque,...,9.0,120.0,40.0,115.86,1,NaN,0.0,0.0,0.00,57.8805
161,215,Route 292,292,87.73,23.64,0.0,C89,162 Copala_1,Complementarias,C89,...,1.0,24.0,180.0,80.25,1,10.0,0.0,0.0,0.00,0.0000

In [117]:
usable_routes.to_csv('Routes_WhereOneSP_HasNoSeq.csv', index=False)

In [116]:
#get route_ids from no_sequence that are not in sp_withSequence
#if the route_id is in sp_withSequence then it's just a stop point in the route that has no seq. & route is mostly complete and therefore usable
#if the route_id is not in sp_withSequence every SP in that route has no seq & route is NOT USABLE AT ALL

#routes where every sp has no seq
unusable_routes = no_sequence[~no_sequence['ROUTE_ID'].isin(sp2024_withSequence['ROUTE_ID'])]

#unique route ids from unusable routes
unusable_routesIDS = unusable_routes['ROUTE_ID'].nunique()
routes_withoutAnySeq = ro2024_df[ro2024_df['ROUTE_ID'].isin(unusable_routes['ROUTE_ID'])]

print(f'Unique values en SITUACION de rutas con todos los SP sin SECUENCIA: {routes_withoutAnySeq['SITUACION'].unique()}')
print(f'Unique values en CLASE de rutas con todos los SP sin SECUENCIA: {routes_withoutAnySeq['CLASE'].unique()}')
print(f'Total de rutas que no tienen SECUENCIA en NI UN SP y no se pueden crear: {len(routes_withoutAnySeq)}')
routes_withoutAnySeq.head()

Unique values en SITUACION de rutas con todos los SP sin SECUENCIA: ['Construcci�n' 'Propuesta' 'Federal']
Unique values en CLASE de rutas con todos los SP sin SECUENCIA: ['Tren ligero' 'SITREN' 'Federal suburbana']
Total de rutas que no tienen SECUENCIA en NI UN SP y no se pueden crear: 42

,ROUTE_ID,ROUTE_NAME,ID_RUTA,TIME,LONGITUD,DISTANCE,RUTA_ACT,RUTA_ANT,CLASE,ORI_DES,...,FLOTA,CAPACIDAD,HEADWAY,TDR,MODE,CORREDOR,DEMANDA1,DEMANDA2,DEMANDA3,F_CORREDOR
647,1104,Route 901,901,NaN,20.48,0.0,L4,NaN,Tren ligero,Tlajomlulco Centro Fray Angelico,...,0.0,6000.0,5.0,40.96,5,NaN,0.0,0.0,0.0,0.0
648,1105,Route 902,902,NaN,20.48,0.0,L4,NaN,Tren ligero,Fray Angelico Tlajomulco Centro,...,0.0,6000.0,5.0,40.97,5,NaN,0.0,0.0,0.0,0.0
649,1108,Route 903,903,NaN,11.08,0.0,SITREN L5,NaN,SITREN,San Agust�n L4,...,0.0,80.0,12.0,30.11,6,NaN,0.0,0.0,0.0,0.0
650,1109,Route 904,904,NaN,11.20,0.0,SITREN L5,NaN,SITREN,San Agust�n L4,...,0.0,80.0,12.0,30.11,6,NaN,0.0,0.0,0.0,0.0
651,1110,Route 905,905,NaN,10.75,0.0,SITREN L6,NaN,SITREN,C�ntaros L4,...,0.0,80.0,12.0,30.11,6,NaN,0.0,0.0,0.0,0.0

In [102]:
routes_withoutAnySeq.to_csv('Routes_WhereEverySP_HasNoFreq.csv', index=False)