# Peak factor x Ponderador

In [1]:
import pandas as pd

Se crea el diccionario de peak factos - periodo

In [2]:
dicc_peak_factors = {
	"EM"	: 0.312238,
	"AP"	: 0.359590,
	"LM"	: 0.373869,
	"EA"	: 0.181566,
	"PP"	: 0.458755,
	"LN"	: 0.533415
}

Agregar a EM priv

In [3]:
EM_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_EM.csv")
EM_priv["Peak Factor"] = dicc_peak_factors["EM"]
EM_priv["Ponderador_x_PF"] = EM_priv["Ponderador"] * dicc_peak_factors["EM"]
EM_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,0,1409701800301,1412000012492,29,5223,8102,EM,0.312238,9.054902
1,Vehículo Privado,0,1409800010031,1409800011576,46,6001,6072,EM,0.312238,14.362948
2,Vehículo Privado,0,1409800011576,1409800010031,69,6072,6001,EM,0.312238,21.544422
3,Vehículo Privado,0,1412000012492,1409701800301,29,8102,5223,EM,0.312238,9.054902
4,Vehículo Privado,0,14097059A,140980128288A,91,5241,6235,EM,0.312238,28.413658

In [4]:
EM_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_EM.csv", index=False)

Agregar a EM publ

In [5]:
EM_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_EM.csv")
EM_publ["Peak Factor"] = dicc_peak_factors["EM"]
EM_publ["Ponderador_x_PF"] = EM_publ["Ponderador"] * dicc_peak_factors["EM"]
EM_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,0,140980243,1407000211185,9,6237,3094,EM,0.312238,2.810142
1,Transporte Público,0,1403900012588,1403900014014,125,212,288,EM,0.312238,39.029750
2,Transporte Público,0,1403900012624,1403900012639,136,216,217,EM,0.312238,42.464368
3,Transporte Público,0,1403900012639,1403900012624,136,217,216,EM,0.312238,42.464368
4,Transporte Público,0,1403900013406,1403900015474,125,241,422,EM,0.312238,39.029750

In [6]:
EM_publ.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_EM.csv", index=False)

Agregar a AP priv

In [7]:
AP_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_AP.csv")
AP_priv["Peak Factor"] = dicc_peak_factors["AP"]
AP_priv["Ponderador_x_PF"] = AP_priv["Ponderador"] * dicc_peak_factors["AP"]
AP_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,4,140440011,1404400010100,27,1031,1005,AP,0.35959,9.70893
1,Vehículo Privado,4,140440011,140970005034A,27,1031,5036,AP,0.35959,9.70893
2,Vehículo Privado,4,141011963,999990005,18,7230,10004,AP,0.35959,6.47262
3,Vehículo Privado,4,141011963,1410100010950,144,7230,7053,AP,0.35959,51.78096
4,Vehículo Privado,4,141240029,141240029,9,9042,9042,AP,0.35959,3.23631

In [8]:
AP_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_AP.csv", index=False)

Agregar a AP público

In [9]:
AP_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_AP.csv")
AP_publ["Peak Factor"] = dicc_peak_factors["AP"]
AP_publ["Ponderador_x_PF"] = AP_publ["Ponderador"] * dicc_peak_factors["AP"]
AP_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,4,140440011,1403900011170,15,1031,96,AP,0.35959,5.39385
1,Transporte Público,4,140440011,1412000015374,15,1031,8315,AP,0.35959,5.39385
2,Transporte Público,4,140970602,1409700201013,118,5242,5079,AP,0.35959,42.43162
3,Transporte Público,4,140972416,1412000010636,53,5387,8015,AP,0.35959,19.05827
4,Transporte Público,4,140980243,1409800011928,9,6237,6099,AP,0.35959,3.23631

In [10]:
AP_publ.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_AP.csv", index=False)

Agregar a LM privado

In [11]:
LM_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_LM.csv")
LM_priv["Peak Factor"] = dicc_peak_factors["LM"]
LM_priv["Ponderador_x_PF"] = LM_priv["Ponderador"] * dicc_peak_factors["LM"]
LM_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,9,140440011,140440011,37,1031,1031,LM,0.373869,13.833153
1,Vehículo Privado,9,140440011,999990005,37,1031,10004,LM,0.373869,13.833153
2,Vehículo Privado,9,140440011,1403900014565,27,1031,337,LM,0.373869,10.094463
3,Vehículo Privado,9,140440011,1404400010100,20,1031,1005,LM,0.373869,7.477380
4,Vehículo Privado,9,140440011,14097059A,27,1031,5241,LM,0.373869,10.094463

In [12]:
LM_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_LM.csv", index=False)

Agregar a LM público

In [13]:
LM_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_LM.csv")
LM_publ["Peak Factor"] = dicc_peak_factors["LM"]
LM_publ["Ponderador_x_PF"] = LM_publ["Ponderador"] * dicc_peak_factors["LM"]
LM_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,9,140440011,140440011,32,1031,1031,LM,0.373869,11.963808
1,Transporte Público,9,140440011,999990005,6,1031,10004,LM,0.373869,2.243214
2,Transporte Público,9,140440011,1403900011359,6,1031,111,LM,0.373869,2.243214
3,Transporte Público,9,140440011,1404400010098,15,1031,1004,LM,0.373869,5.608035
4,Transporte Público,9,140440011,1404400010100,15,1031,1005,LM,0.373869,5.608035

In [14]:
LM_publ.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_LM.csv", index=False)

Agregar a EA privado

In [15]:
EA_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_EA.csv")
EA_priv["Peak Factor"] = dicc_peak_factors["EA"]
EA_priv["Ponderador_x_PF"] = EA_priv["Ponderador"] * dicc_peak_factors["EA"]
EA_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,12,140440011,140440011,104,1031,1031,EA,0.181566,18.882864
1,Vehículo Privado,12,140440011,1404400540401,27,1031,1033,EA,0.181566,4.902282
2,Vehículo Privado,12,140440011,1409707771780,114,1031,5247,EA,0.181566,20.698524
3,Vehículo Privado,12,140440026,140440011,10,1032,1031,EA,0.181566,1.815660
4,Vehículo Privado,12,140440026,140440026,10,1032,1032,EA,0.181566,1.815660

In [16]:
EA_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_EA.csv", index=False)

Agregar a EA público

In [17]:
EA_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_EA.csv")
EA_publ["Peak Factor"] = dicc_peak_factors["EA"]
EA_publ["Ponderador_x_PF"] = EA_publ["Ponderador"] * dicc_peak_factors["EA"]
EA_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,12,140440011,1404400020115,4,1031,1014,EA,0.181566,0.726264
1,Transporte Público,12,140440011,1404400540401,15,1031,1033,EA,0.181566,2.723490
2,Transporte Público,12,140440011,1404400540416,15,1031,1034,EA,0.181566,2.723490
3,Transporte Público,12,140440011,1407000010045,15,1031,3002,EA,0.181566,2.723490
4,Transporte Público,12,140440026,1404400540401,30,1032,1033,EA,0.181566,5.446980

In [18]:
EA_publ.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_EA.csv", index=False)

Agregar a PP privado

In [19]:
PP_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_PP.csv")
PP_priv["Peak Factor"] = dicc_peak_factors["PP"]
PP_priv["Ponderador_x_PF"] = PP_priv["Ponderador"] * dicc_peak_factors["PP"]
PP_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,18,140440011,140440011,108,1031,1031,PP,0.458755,49.545540
1,Vehículo Privado,18,140440011,140970123,10,1031,5222,PP,0.458755,4.587550
2,Vehículo Privado,18,140440011,1404400010083,10,1031,1003,PP,0.458755,4.587550
3,Vehículo Privado,18,140440011,1404400020115,7,1031,1014,PP,0.458755,3.211285
4,Vehículo Privado,18,140440011,1404400020153,7,1031,1018,PP,0.458755,3.211285

In [20]:
PP_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_PP.csv", index=False)

Agregar a PP público

In [21]:
PP_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_PP.csv")
PP_publ["Peak Factor"] = dicc_peak_factors["PP"]
PP_publ["Ponderador_x_PF"] = PP_publ["Ponderador"] * dicc_peak_factors["PP"]
PP_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,18,140440011,140440011,6,1031,1031,PP,0.458755,2.752530
1,Transporte Público,18,140440011,999990005,6,1031,10004,PP,0.458755,2.752530
2,Transporte Público,18,140440011,1404400020134,7,1031,1016,PP,0.458755,3.211285
3,Transporte Público,18,140440011,1404400540401,15,1031,1033,PP,0.458755,6.881325
4,Transporte Público,18,140440011,1404400540416,15,1031,1034,PP,0.458755,6.881325

Agregar a LN privado

In [22]:
LN_priv = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_LN.csv")
LN_priv["Peak Factor"] = dicc_peak_factors["LN"]
LN_priv["Ponderador_x_PF"] = LN_priv["Ponderador"] * dicc_peak_factors["LN"]
LN_priv.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Vehículo Privado,21,140440011,1404400020115,7,1031,1014,LN,0.533415,3.733905
1,Vehículo Privado,21,140440011,140440002005A,7,1031,1013,LN,0.533415,3.733905
2,Vehículo Privado,21,140440026,140440026,10,1032,1032,LN,0.533415,5.334150
3,Vehículo Privado,21,140701467,140701467,23,3133,3133,LN,0.533415,12.268545
4,Vehículo Privado,21,140970015,1409700213842,19,5060,5081,LN,0.533415,10.134885

In [23]:
LN_priv.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_VP_LN.csv", index=False)

Agregar a LN público

In [24]:
LN_publ = pd.read_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_LN.csv")
LN_publ["Peak Factor"] = dicc_peak_factors["LN"]
LN_publ["Ponderador_x_PF"] = LN_publ["Ponderador"] * dicc_peak_factors["LN"]
LN_publ.head()

,Modo,Hora_inicio,Origen,Destino,Ponderador,Origen_ageb,Destino_ageb,Periodo,Peak Factor,Ponderador_x_PF
0,Transporte Público,21,140440011,1409700053575,11,1031,5049,LN,0.533415,5.867565
1,Transporte Público,21,140701467,1409708223077,136,3133,5279,LN,0.533415,72.544440
2,Transporte Público,21,140970015,1409700320053,59,5060,5135,LN,0.533415,31.471485
3,Transporte Público,21,140970602,1409700250369,28,5242,5088,LN,0.533415,14.935620
4,Transporte Público,21,140970602,1409700350138,108,5242,5169,LN,0.533415,57.608820

In [25]:
LN_publ.to_csv(r"C:\proyectos\red-vial-guadalajara\OneDrive_2026-08-25\Matriz Origen Destino\Matrices filtradas por periodo y modo (completas)\matriz_TP_LN.csv", index=False)