In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import os
import re

In [2]:
folder = r"C:\Users\Roberto Ponce López\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey (1)\Modelación Urbana - Red Vial Guadalajara"

### Warnings from Network Check
- ran with Zones with demand data

In [3]:
warnings_txt = os.path.join(folder, "Zones Connectivity Test", "with final filt", "all_zones_more_than_1conn.txt")

with open(warnings_txt, "r", encoding="utf-8") as archivo:
    messages = archivo.read()

pairs = re.findall(
    r"between Zone (\d+) and Zone (\d+)",
    messages
)

errors = pd.DataFrame(
    pairs,
    columns=["origin_zone", "destination_zone"]
).astype(int)

print(f"Check network consistency: {len(errors):,} warnings")

errors

Check network consistency: 162,038 warnings

        origin_zone  destination_zone
0                 1               443
1                 1              1012
2                 1              5028
3                 1              5082
4                 1              5092
...             ...               ...
162033         9053              8333
162034         9053              8373
162035         9053              8410
162036         9053              8413
162037         9053              8426

[162038 rows x 2 columns]

In [4]:
origin_problems = (
    errors["origin_zone"]
    .value_counts()
    .rename_axis("zone_id")
    .reset_index(name="fails_as_origin")
)

destination_problems = (
    errors["destination_zone"]
    .value_counts()
    .rename_axis("zone_id")
    .reset_index(name="fails_as_destination")
)

zone_problems = (
    origin_problems
    .merge(
        destination_problems,
        on="zone_id",
        how="outer"
    )
    .fillna(0)
)

zone_problems[["fails_as_origin", "fails_as_destination"]] = (
    zone_problems[["fails_as_origin", "fails_as_destination"]].astype(int)
)


zone_problems["total"] = (
    zone_problems["fails_as_origin"]
    + zone_problems["fails_as_destination"]
)

zone_problems = zone_problems.sort_values(
    "total",
    ascending=False
)

zone_problems

      zone_id  fails_as_origin  fails_as_destination  total
454      1012             4119                  4119   8238
812      5092             4119                  4119   8238
1954     8373             4117                  4117   8234
2064     8483             2095                  2095   4190
2006     8425             2095                  2095   4190
...       ...              ...                   ...    ...
688      4069               19                     1     20
650      4016               11                     2     13
637      4003               11                     2     13
707      4094               11                     1     12
706      4093               10                     1     11

[2182 rows x 4 columns]

In [5]:
# 2. Cuántas zonas tienen cada cantidad de fallas como origen
print(zone_problems["fails_as_origin"].value_counts().sort_index())
print()
# 3. Cuántas zonas tienen cada cantidad de fallas como destino
print(zone_problems["fails_as_destination"].value_counts().sort_index())

fails_as_origin
10        11
11        12
19         1
20        60
21         1
23         2
24        60
33         6
34         5
35         1
36         7
37         2
38      1988
83         1
84         1
2094       2
2095       6
4115       5
4117       6
4119       5
Name: count, dtype: int64

fails_as_destination
1          4
2         62
23         1
24        60
36         6
38        16
39         2
40      1987
74         9
75        10
84         1
2089       1
2093       1
2094       1
2095       7
4108       2
4111       2
4117       2
4119       8
Name: count, dtype: int64

In [6]:
zone_problems[
    (zone_problems["fails_as_origin"] > 1000)
    | (zone_problems["fails_as_destination"] > 1000)
]

      zone_id  fails_as_origin  fails_as_destination  total
454      1012             4119                  4119   8238
812      5092             4119                  4119   8238
1954     8373             4117                  4117   8234
2064     8483             2095                  2095   4190
2006     8425             2095                  2095   4190
1536     7188             2095                  2095   4190
2181     9054             2095                  2095   4190
748      5028             2095                  2095   4190
938      5218             2095                  2095   4190
2021     8440             2094                  2094   4188
1029     5309             4119                    38   4157
1001     5281             4119                    38   4157
769      5049             4119                    38   4157
1889     8308               36                  4119   4155
1994     8413               36                  4119   4155
2007     8426               36                  4119   4155
442       443               36                  4119   4155
2017     8436             4117                    38   4155
1991     8410               36                  4119   4155
1313     6203             4117                    38   4155
1070     5350             4117                    38   4155
940      5220               35                  4119   4154
802      5082               36                  4117   4153
478      1036             4115                    38   4153
1571     7223             4115                    38   4153
968      5248             4117                    36   4153
970      5250             4117                    36   4153
1955     8374             4115                    36   4151
2163     9036             4115                    36   4151
2162     9035             4115                    36   4151
1779     8198               34                  4111   4145
1914     8333               34                  4111   4145
1312     6202               33                  4108   4141
1322     6212               33                  4108   4141
832      5112               23                  2095   2118
1539     7191             2094                    23   2117
941      5221               23                  2093   2116
1303     6193               21                  2089   2110

In [20]:
zone_problems.to_csv(
    os.path.join(folder, "Zones Connectivity Test", "unreachable_zones_summary.csv"),
    index=False
)

In [31]:
isolated_group = zone_problems[
    zone_problems["fails_as_origin"] == 29
].copy()

print(len(isolated_group))
isolated_group["zone_id"].tolist()

2043

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 80,
 65,
 66,
 67,
 68,
 69,
 70,
 13,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 9005,
 9006,
 8537,
 8538,
 8539,
 8540,
 8541,
 8542,
 9013,
 9014,
 8545,
 8546,
 9001,
 9002,
 9003,
 10,
 112,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 56,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 64,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 72,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 144,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 88,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 96,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 104,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 176,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 120,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 128,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 136,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 208,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 152,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 160,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 168,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 240,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 184,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 192,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 200,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 272,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 216,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 224,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 232,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 304,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 248,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 256,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 264,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 336,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 280,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 288,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 296,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 368,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 312,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 320,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 328,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 400,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 344,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 352,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 360,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 432,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 376,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 384,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 392,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 1021,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 408,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 416,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 424,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 2014,
 1038,
 1039,
 2001,
 2002,
 2003,
 2004,
 2005,
 440,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 1005,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 1013,
 441,
 442,
 443,
 1001,
 1002,
 1003,
 1004,
 3026,
 3011,
 3012,
 3013,
 3014,
 3015,
 3016,
 3017,
 1029,
 3019,
 3020,
 3021,
 3022,
 3023,
 3024,
 3025,
 1037,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 2006,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 3058,
 3043,
 3044,
 3045,
 3046,
 3047,
 3048,
 3049,
 3002,
 3051,
 3052,
 3053,
 3054,
 3055,
 3056,
 3057,
 3010,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 3001,
 3018,
 3003,
 3004,
 3005,
 3006,
 3007,
 3008,
 3009,
 3090,
 3075,
 3076,
 3077,
 3078,
 3079,
 3080,
 3081,
 3034,
 3083,
 3084,
 3085,
 3086,
 3087,
 3088,
 3089,
 3042,
 3027,
 3028,
 3029,
 3030,
 3031,
 3032,
 3033,
 3050,
 3035,
 3036,
 3037,
 3038,
 3039,
 3040,
 3041,
 3122,
 3107,
 3108,
 3109,
 3110,
 3111,
 3112,
 3113,
 3066,
 3115,
 3116,
 3117,
 3118,
 3119,
 3120,
 3121,
 3074,
 3059,
 3060,
 3061,
 3062,
 3063,
 3064,
 3065,
 3082,
 3067,
 3068,
 3069,
 3070,
 3071,
 3072,
 3073,
 5021,
 5006,
 5007,
 5008,
 5009,
 5010,
 5011,
 5012,
 3098,
 5014,
 5015,
 5016,
 5017,
 5018,
 5019,
 5020,
 3106,
 3091,
 3092,
 3093,
 3094,
 3095,
 3096,
 3097,
 3114,
 3099,
 3100,
 3101,
 3102,
 3103,
 3104,
 3105,
 5053,
 5038,
 5039,
 5040,
 5041,
 5042,
 5043,
 5044,
 3130,
 5046,
 5047,
 5048,
 5050,
 5051,
 5052,
 5005,
 3123,
 3124,
 3125,
 3126,
 3127,
 3128,
 3129,
 5013,
 3131,
 3132,
 3133,
 5001,
 5002,
 5003,
 5004,
 5085,
 5070,
 5071,
 5072,
 5073,
 5074,
 5075,
 5076,
 5029,
 5078,
 5079,
 5080,
 5081,
 5082,
 5083,
 5084,
 5037,
 5022,
 5023,
 5024,
 5025,
 5026,
 5027,
 5028,
 5045,
 5030,
 5031,
 5032,
 5033,
 5034,
 5035,
 5036,
 5102,
 5103,
 5104,
 5106,
 5107,
 5108,
 5109,
 5061,
 5110,
 5111,
 5113,
 5114,
 5115,
 5117,
 5069,
 5054,
 5055,
 5056,
 5058,
 5059,
 5060,
 5077,
 5062,
 5063,
 5064,
 5065,
 5066,
 5067,
 5068,
 5135,
 5136,
 5137,
 5138,
 5139,
 5140,
 5141,
 5126,
 5143,
 5144,
 5145,
 5146,
 5147,
 5148,
 5149,
 5134,
 5087,
 5088,
 5089,
 5090,
 5091,
 5093,
 5142,
 5095,
 5096,
 5097,
 5098,
 5099,
 5100,
 5101,
 5086,
 5167,
 5168,
 5169,
 5170,
 5171,
 5172,
 5173,
 5158,
 5175,
 5176,
 5177,
 5178,
 5179,
 5180,
 5181,
 5166,
 5120,
 5122,
 5123,
 5124,
 5125,
 5174,
 5127,
 5128,
 5129,
 5130,
 5131,
 5132,
 5133,
 5118,
 5199,
 5200,
 5201,
 5202,
 5203,
 5204,
 5205,
 5190,
 5207,
 5208,
 5209,
 5210,
 5211,
 5212,
 5213,
 5198,
 5151,
 5152,
 5153,
 5154,
 5155,
 5156,
 5157,
 5206,
 5159,
 5160,
 5161,
 5162,
 5163,
 5164,
 5165,
 5150,
 5231,
 5232,
 5233,
 5234,
 5235,
 5236,
 5237,
 5222,
 5239,
 5240,
 5241,
 5242,
 5243,
 5244,
 5245,
 5230,
 5183,
 5184,
 5185,
 5186,
 5187,
 5188,
 5189,
 5238,
 5191,
 5192,
 5193,
 5194,
 5195,
 5196,
 5197,
 5182,
 5264,
 5265,
 5266,
 5267,
 5268,
 5269,
 5254,
 5255,
 5272,
 5273,
 5274,
 5275,
 5276,
 5277,
 5262,
 5263,
 5215,
 5216,
 5219,
 5270,
 5271,
 5223,
 5224,
 5225,
 5226,
 5227,
 5228,
 5229,
 5214,
 5297,
 5298,
 5299,
 5300,
 5301,
 5286,
 5287,
 5288,
 5305,
 5306,
 5307,
 5308,
 5294,
 5295,
 5296,
 5249,
 5251,
 5252,
 5253,
 5302,
 5303,
 5304,
 5256,
 5257,
 5258,
 5259,
 5260,
 5261,
 5246,
 5247,
 5329,
 5330,
 5331,
 5332,
 5333,
 5318,
 5319,
 5320,
 5337,
 5338,
 5339,
 5340,
 5341,
 5326,
 5327,
 5328,
 5281,
 5282,
 5283,
 5284,
 5285,
 5334,
 5335,
 5336,
 5289,
 5290,
 5291,
 5292,
 5293,
 5278,
 5279,
 5280,
 5361,
 5362,
 5363,
 5364,
 5365,
 5351,
 5352,
 5370,
 5371,
 5372,
 5373,
 5358,
 5359,
 5360,
 5313,
 5314,
 5315,
 5316,
 5317,
 5366,
 5321,
 5322,
 5323,
 5324,
 5325,
 5310,
 5311,
 5312,
 6003,
 6004,
 6005,
 6006,
 6007,
 5382,
 5383,
 5384,
 6011,
 6012,
 6013,
 6014,
 6015,
 5390,
 6001,
 6002,
 5345,
 5346,
 5347,
 5348,
 5349,
 6008,
 6009,
 6010,
 5353,
 5354,
 5355,
 5356,
 5357,
 5342,
 5343,
 6035,
 6036,
 6037,
 6038,
 6039,
 6024,
 6025,
 6026,
 6043,
 6044,
 6045,
 6046,
 6047,
 6032,
 6033,
 6034,
 5377,
 5378,
 5379,
 ...]

In [8]:
zone_problems["fails_as_origin"].value_counts().sort_index()

fails_as_origin
43         1
139     2049
140        5
141        2
142        1
143        2
144        2
145        1
152        1
2106      96
2202      43
Name: count, dtype: int64

In [9]:
zone_problems["fails_as_destination"].value_counts().sort_index()

fails_as_destination
43         1
139     2015
140       47
141        1
2106      96
2202      43
Name: count, dtype: int64

In [10]:
# Zonas que prácticamente NO pueden salir
bad_origins = zone_problems[
    zone_problems["fails_as_origin"] > 2000
].sort_values("fails_as_origin", ascending=False)

# Zonas a las que prácticamente NO se puede llegar
bad_destinations = zone_problems[
    zone_problems["fails_as_destination"] > 2000
].sort_values("fails_as_destination", ascending=False)

# Zonas graves en ambos sentidos
bad_both = zone_problems[
    (zone_problems["fails_as_origin"] > 2000) &
    (zone_problems["fails_as_destination"] > 2000)
]

print("Bad origins:", len(bad_origins))
print("Bad destinations:", len(bad_destinations))
print("Bad both:", len(bad_both))

Bad origins: 139
Bad destinations: 139
Bad both: 139

In [11]:
bad_both[[
    "zone_id",
    "fails_as_origin",
    "fails_as_destination"
]].sort_values(
    "fails_as_origin",
    ascending=False
)

      zone_id  fails_as_origin  fails_as_destination
917      5176             2202                  2202
686      4052             2202                  2202
1016     5275             2202                  2202
900      5159             2202                  2202
959      5218             2202                  2202
...       ...              ...                   ...
670      4036             2106                  2106
719      4085             2106                  2106
669      4035             2106                  2106
721      4087             2106                  2106
674      4040             2106                  2106

[139 rows x 3 columns]

In [12]:
bad_both["fails_as_origin"].value_counts()

fails_as_origin
2106    96
2202    43
Name: count, dtype: int64

In [13]:
group_2202 = bad_both[
    bad_both["fails_as_origin"] == 2202
]

group_2106 = bad_both[
    bad_both["fails_as_origin"] == 2106
]

print("Completely disconnected:", len(group_2202))
print("Large isolated group:", len(group_2106))

Completely disconnected: 43
Large isolated group: 96

In [14]:
group_2202

      zone_id  fails_as_origin  fails_as_destination  total
917      5176             2202                  2202   4404
686      4052             2202                  2202   4404
1016     5275             2202                  2202   4404
900      5159             2202                  2202   4404
959      5218             2202                  2202   4404
978      5237             2202                  2202   4404
698      4064             2202                  2202   4404
651      4017             2202                  2202   4404
678      4044             2202                  2202   4404
804      5063             2202                  2202   4404
805      5064             2202                  2202   4404
605      3104             2202                  2202   4404
769      5028             2202                  2202   4404
806      5065             2202                  2202   4404
657      4023             2202                  2202   4404
720      4086             2202                  2202   4404
488      2007             2202                  2202   4404
489      2008             2202                  2202   4404
653      4019             2202                  2202   4404
724      4090             2202                  2202   4404
909      5168             2202                  2202   4404
2202     9054             2202                  2202   4404
454      1012             2202                  2202   4404
808      5067             2202                  2202   4404
903      5162             2202                  2202   4404
889      5148             2202                  2202   4404
818      5077             2202                  2202   4404
696      4062             2202                  2202   4404
700      4066             2202                  2202   4404
432       433             2202                  2202   4404
1341     6210             2202                  2202   4404
1353     6222             2202                  2202   4404
1443     7074             2202                  2202   4404
1444     7075             2202                  2202   4404
1510     7141             2202                  2202   4404
1514     7145             2202                  2202   4404
1516     7147             2202                  2202   4404
1557     7188             2202                  2202   4404
1569     7200             2202                  2202   4404
1889     8287             2202                  2202   4404
2027     8425             2202                  2202   4404
2081     8479             2202                  2202   4404
2085     8483             2202                  2202   4404