In [1]:
import pandas as pd

### Read LR, LR de Transporte Masivo y SP

In [ ]:
LR_csv = r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Transporte Publico\Rutas Operando\RutasOperando2024_Attributes.csv'
LR = pd.read_csv(LR_csv)

In [7]:
LR_BRT_TrenLigero_csv = r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Transporte Publico\Rutas Operando BRT y Tren Ligero\rutas_operando_transporte_masivo.csv'
LR_BRT_TrenLigero = pd.read_csv(LR_BRT_TrenLigero_csv)

In [8]:
SP_csv = r'C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Transporte Publico\Puntos de Parada\PuntosParada2024_Attributes.csv'
SP = pd.read_csv(SP_csv)

### __Get SP that have ROUTE_ID in LR_BRT_TrenLigero__ (SP that belong to a BRT/Tren Ligero Line)

In [26]:
SP_TransporteMasivo = SP[SP['ROUTE_ID'].isin(LR_BRT_TrenLigero['ROUTE_ID'])]
SP_TransporteMasivo_NoSeq = SP_TransporteMasivo[SP_TransporteMasivo['SECUENCIA'].isna()]
SP_TransporteMasivo_WithSeq = SP_TransporteMasivo[SP_TransporteMasivo['SECUENCIA'].notna()]

print(f'The routes: {(SP_TransporteMasivo_NoSeq['ROUTE_ID'].unique()).tolist()} have STOP POINTS with no sequence')
print('BUT ONLY, Routes 1104 & 1105 have ALL Stop Point with NO SEQUENCE (NaN)')
SP_TransporteMasivo_NoSeq[~SP_TransporteMasivo_NoSeq["ROUTE_ID"].isin(SP_TransporteMasivo_WithSeq["ROUTE_ID"])]

The routes: [1104, 1105, 705, 706, 709, 707, 708, 710, 711, 712, 990, 713, 1061, 1025, 995, 1063, 1022, 715] have STOP POINTS with no sequence
BUT ONLY, Routes 1104 & 1105 have ALL Stop Point with NO SEQUENCE (NaN)

,ID,ROUTE_ID,PASS_COUNT,MILEPOST,STOP_ID,USERID,TRACK,SECUENCIA,LINK_ID,DIR,NODE,TIPO
8474,44737,1104,1,2.690978,44737,NaN,NaN,NaN,NaN,NaN,106124,NaN
8666,44736,1104,1,0.067602,44736,NaN,NaN,NaN,NaN,NaN,4547,NaN
41431,44751,1105,1,20.437260,44751,NaN,NaN,NaN,NaN,NaN,4547,NaN
41541,44750,1105,1,17.813770,44750,NaN,NaN,NaN,NaN,NaN,106124,NaN
41542,44749,1105,1,15.331995,44749,NaN,NaN,NaN,NaN,NaN,106125,NaN
41936,44748,1105,1,12.839602,44748,NaN,NaN,NaN,NaN,NaN,106127,NaN
42093,44747,1105,1,10.065342,44747,NaN,NaN,NaN,NaN,NaN,106129,NaN
42094,44746,1105,1,6.109821,44746,NaN,NaN,NaN,NaN,NaN,62562,NaN
42095,44745,1105,1,4.078145,44745,NaN,NaN,NaN,NaN,NaN,106133,NaN
42096,44744,1105,1,0.015013,44744,NaN,NaN,NaN,NaN,NaN,106135,NaN
43783,44743,1104,1,20.460987,44743,NaN,NaN,NaN,NaN,NaN,106135,NaN
43784,44742,1104,1,16.391588,44742,NaN,NaN,NaN,NaN,NaN,106133,NaN
43785,44741,1104,1,14.343491,44741,NaN,NaN,NaN,NaN,NaN,62562,NaN
43786,44740,1104,1,10.410492,44740,NaN,NaN,NaN,NaN,NaN,106129,NaN
43787,44739,1104,1,7.667083,44739,NaN,NaN,NaN,NaN,NaN,106127,NaN
43788,44738,1104,1,5.178213,44738,NaN,NaN,NaN,NaN,NaN,106125,NaN

### __Rutas que NO SIRVEN__ (1104 y 1105)

#### porque __SITUACION == "Construccion"__

In [28]:
LR_BRT_TrenLigero[LR_BRT_TrenLigero['ROUTE_ID'].isin([1104,1105])]

,ROUTE_ID,ROUTE_NAME,ID_RUTA,TIME,LONGITUD,DISTANCE,RUTA_ACT,RUTA_ANT,CLASE,ORI_DES,...,FLOTA,CAPACIDAD,HEADWAY,TDR,MODE,CORREDOR,DEMANDA1,DEMANDA2,DEMANDA3,F_CORREDOR
16,1104,Route 901,901,NaN,20.48,0,L4,NaN,Tren ligero,Tlajomlulco Centro Fray Angelico,...,0,6000,5,40.96,5,NaN,0,0,0.0,0
17,1105,Route 902,902,NaN,20.48,0,L4,NaN,Tren ligero,Fray Angelico Tlajomulco Centro,...,0,6000,5,40.97,5,NaN,0,0,0.0,0